const pinyinDict = {
    "之": "zhī",
    "不": "bù / bú",
    "一": "yī",
    "人": "rén",
    "以": "yǐ",
    "有": "yǒu",
    "了": "le / liǎo / liào",
    "为": "wéi / wèi",
    "道": "dào",
    "是": "shì",
    "子": "zǐ / zi",
    "的": "de / dí / dì",
    "来": "lái",
    "大": "dà / dài",
    "也": "yě",
    "十": "shí",
    "其": "qí",
    "上": "shàng",
    "二": "èr",
    "而": "ér",
    "中": "zhōng / zhòng",
    "曰": "yuē",
    "下": "xià",
    "于": "yú",
    "三": "sān",
    "得": "dé / de / děi",
    "在": "zài",
    "年": "nián",
    "我": "wǒ",
    "他": "tā",
    "王": "wáng",
    "说": "shuì / shuō",
    "事": "shì",
    "见": "jiàn / xiàn",
    "将": "jiāng / jiàng",
    "者": "zhě",
    "去": "qù",
    "日": "rì",
    "天": "tiān",
    "州": "zhōu",
    "出": "chū",
    "后": "hòu",
    "又": "yòu",
    "自": "zì",
    "此": "cǐ",
    "个": "gè",
    "时": "shí",
    "无": "wú",
    "军": "nan",
    "太": "tài",
    "这": "zhè / zhèi",
    "与": "yú / yǔ / yù",
    "月": "yuè",
    "所": "suǒ",
    "家": "jiā",
    "如": "rú",
    "知": "zhī",
    "你": "nǐ",
    "里": "lǐ",
    "公": "gōng",
    "行": "háng / xíng / xìng",
    "可": "kě",
    "使": "shǐ",
    "到": "dào",
    "四": "sì",
    "至": "zhì",
    "五": "wǔ",
    "那": "nǎ / nà / nèi",
    "官": "guān",
    "书": "shū",
    "生": "shēng",
    "小": "xiǎo",
    "言": "yán",
    "何": "hé",
    "相": "xiāng / xiàng",
    "兵": "bīng",
    "今": "jīn",
    "都": "dōu / dū",
    "南": "nán",
    "山": "shān",
    "就": "jìu",
    "只": "qí / zhī / zhǐ",
    "正": "zhēng / zhèng",
    "前": "qián",
    "明": "míng",
    "东": "dōng",
    "着": "zhāo / zháo / zhe / zhù",
    "门": "mén",
    "帝": "dì",
    "等": "děng",
    "文": "wén",
    "国": "guó",
    "百": "bǎi",
    "西": "xī",
    "心": "xīn",
    "安": "ān",
    "然": "rán",
    "要": "yāo / yào",
    "好": "hǎo / hào",
    "入": "rù",
    "回": "huí",
    "同": "tóng",
    "从": "cōng / cóng / zòng",
    "老": "lǎo",
    "两": "liǎng",
    "进": "jìn",
    "已": "yǐ",
    "马": "mǎ",
    "起": "qǐ",
    "云": "yún",
    "元": "yuán",
    "当": "dāng / dàng",
    "及": "jí",
    "未": "wèi",
    "臣": "chén",
    "便": "biàn / pián",
    "还": "hái / huán / huàn",
    "地": "de / dì",
    "夫": "fū",
    "城": "chéng",
    "过": "guò",
    "看": "kān / kàn",
    "令": "lìng",
    "儿": "ér / er",
    "多": "duō",
    "六": "lìu",
    "用": "yòng",
    "方": "fāng",
    "士": "shì",
    "乃": "nǎi",
    "分": "fēn / fèn",
    "长": "cháng / zhǎng",
    "金": "jīn",
    "平": "píng",
    "能": "néng",
    "故": "gù",
    "则": "zé",
    "命": "mìng",
    "万": "wàn",
    "头": "tóu / tou",
    "先": "xiān",
    "史": "shǐ",
    "名": "míng",
    "皆": "jiē",
    "主": "zhǔ",
    "死": "sǐ",
    "司": "sī",
    "成": "chéng / chèng",
    "问": "wèn",
    "武": "wǔ",
    "外": "wài",
    "复": "fù",
    "水": "shuǐ",
    "八": "bā",
    "请": "qǐng",
    "七": "qī",
    "师": "shī",
    "宗": "zōng",
    "高": "gāo",
    "千": "qiān",
    "诸": "zhū",
    "听": "tīng / tìng",
    "内": "nèi",
    "若": "ruò",
    "朝": "cháo / zhāo",
    "身": "shēn",
    "尚": "shàng",
    "李": "lǐ",
    "和": "hé / hè / huó / huò",
    "作": "zuò",
    "北": "běi",
    "定": "dìng",
    "县": "xiàn",
    "张": "zhāng",
    "女": "nǔ: / nv",
    "因": "yīn",
    "阳": "yáng",
    "面": "miàn",
    "数": "shǔ / shù / shuò",
    "府": "fǔ",
    "江": "jiāng",
    "即": "jí",
    "德": "dé",
    "亦": "yì",
    "把": "bǎ / bà",
    "河": "hé",
    "本": "běn",
    "守": "shǒu",
    "礼": "lǐ",
    "九": "jǐu",
    "世": "shì",
    "君": "nan",
    "众": "zhòng",
    "白": "bái",
    "开": "kāi",
    "闻": "wén",
    "走": "zǒu",
    "立": "lì",
    "并": "bìng",
    "意": "yì",
    "部": "bù",
    "亲": "qīn / qìng",
    "才": "cái",
    "处": "chǔ / chù",
    "皇": "huáng",
    "常": "cháng",
    "必": "bì",
    "法": "fǎ",
    "非": "fēi",
    "会": "huì / kuài",
    "欲": "yù",
    "们": "men",
    "手": "shǒu",
    "民": "mín",
    "谓": "wèi",
    "么": "ma / me / yāo",
    "声": "shēng",
    "且": "qiě",
    "少": "shǎo / shào",
    "遂": "suì / suí",
    "路": "lù",
    "诏": "zhào",
    "玉": "yù",
    "叫": "jiào",
    "位": "wèi",
    "氏": "shì",
    "郎": "láng",
    "左": "zuǒ",
    "甚": "shèn",
    "余": "yú",
    "风": "fēng",
    "弟": "dì",
    "度": "dù",
    "初": "chū",
    "义": "yì",
    "各": "gè",
    "杀": "shā",
    "父": "fù",
    "归": "guī",
    "侍": "shì",
    "花": "huā",
    "口": "kǒu",
    "神": "shén",
    "发": "fā / fà",
    "第": "dì",
    "光": "guāng",
    "取": "qǔ",
    "坐": "zuò",
    "应": "yīng / yìng",
    "遣": "qiǎn",
    "矣": "yǐ",
    "学": "xué",
    "京": "jīng",
    "间": "jiān / jiàn",
    "卷": "juǎn / juàn",
    "春": "chūn",
    "酒": "jǐu",
    "字": "zì",
    "重": "chóng / zhòng",
    "没": "méi / mò",
    "几": "jī / jǐ",
    "右": "yòu",
    "祖": "zǔ",
    "罢": "bà / ba",
    "既": "jì",
    "经": "jīng",
    "往": "wǎng / wàng",
    "再": "zài",
    "汉": "hàn",
    "宝": "bǎo",
    "黄": "huáng",
    "边": "biān",
    "通": "tōng",
    "笑": "xiào",
    "御": "yù",
    "节": "jié / jiē",
    "宫": "gōng",
    "却": "què",
    "对": "duì",
    "兴": "xīng / xìng",
    "周": "zhōu",
    "母": "mǔ",
    "真": "zhēn",
    "石": "dàn / shí",
    "陈": "chén",
    "话": "huà",
    "打": "dá / dǎ",
    "尽": "jǐn / jìn",
    "气": "qì",
    "直": "zhí",
    "情": "qíng",
    "传": "chuán / zhuàn",
    "海": "hǎi",
    "齐": "qí",
    "难": "nán / nàn",
    "乐": "lè / yuè",
    "己": "jǐ",
    "拜": "bài",
    "吾": "wú",
    "清": "qīng",
    "合": "gě / hé",
    "夜": "yè",
    "做": "zuò",
    "居": "jū",
    "刘": "líu",
    "龙": "lóng",
    "郡": "nan",
    "奏": "zòu",
    "钱": "qián",
    "置": "zhì",
    "功": "gōng",
    "封": "fēng",
    "住": "zhù",
    "原": "yuán",
    "兄": "xiōng",
    "想": "xiǎng",
    "虽": "suī",
    "爷": "yé",
    "举": "jǔ",
    "实": "shí",
    "岁": "suì",
    "向": "xiàng",
    "贼": "zéi",
    "卿": "qīng",
    "被": "bèi",
    "敢": "gǎn",
    "领": "lǐng",
    "议": "yì",
    "望": "wàng",
    "思": "sī",
    "别": "bié / biè",
    "制": "zhì",
    "注": "zhù",
    "许": "xǔ",
    "送": "sòng",
    "信": "xìn",
    "些": "xiē",
    "姐": "jiě",
    "次": "cì",
    "政": "zhèng",
    "受": "shòu",
    "求": "qíu",
    "秋": "qīu",
    "加": "jiā",
    "古": "gǔ",
    "衣": "yī / yì",
    "改": "gǎi",
    "服": "fú",
    "娘": "niáng",
    "远": "yuǎn",
    "侯": "hóu",
    "解": "jiě / jiè / xiè",
    "林": "lín",
    "流": "líu",
    "给": "gěi / jǐ",
    "理": "lǐ",
    "孙": "sūn",
    "卒": "cù / zú",
    "忠": "zhōng",
    "奉": "fèng",
    "首": "shǒu",
    "留": "líu",
    "房": "fáng",
    "战": "zhàn",
    "连": "lián",
    "喜": "xǐ",
    "罪": "zuì",
    "称": "chèn / chēng / chèng",
    "物": "wù",
    "新": "xīn",
    "善": "shàn",
    "刺": "cì",
    "食": "shí / sì",
    "宜": "yí",
    "教": "jiāo / jiào",
    "广": "guǎng",
    "更": "gēng / gèng",
    "章": "zhāng",
    "户": "hù",
    "吃": "chī / jí",
    "或": "huò",
    "观": "guān / guàn",
    "报": "bào",
    "赐": "cì",
    "保": "bǎo",
    "建": "jiàn",
    "引": "yǐn",
    "力": "lì",
    "关": "guān",
    "色": "sè / shǎi",
    "殿": "diàn",
    "随": "suí",
    "降": "jiàng / xiáng",
    "圣": "shèng",
    "任": "rèn",
    "宋": "sòng",
    "治": "zhì",
    "台": "tái",
    "告": "gào",
    "乱": "luàn",
    "半": "bàn",
    "旧": "jìu",
    "计": "jì",
    "待": "dāi / dài",
    "放": "fàng",
    "青": "qīng",
    "省": "shěng / xǐng",
    "乎": "hū",
    "始": "shǐ",
    "吏": "lì",
    "带": "dài",
    "宣": "xuān",
    "转": "zhuǎn / zhuàn",
    "病": "bìng",
    "姓": "xìng",
    "香": "xiāng",
    "杨": "yáng",
    "失": "shī",
    "妇": "fù",
    "银": "yín",
    "动": "dòng",
    "论": "lún / lùn",
    "宁": "níng",
    "卫": "wèi",
    "孝": "xiào",
    "但": "dàn",
    "由": "yóu",
    "甲": "jiǎ",
    "差": "chā / chà / chāi / cī",
    "镇": "zhèn",
    "吴": "wú",
    "魏": "wèi",
    "诗": "shī",
    "总": "zǒng",
    "交": "jiāo",
    "寻": "xún",
    "足": "zú",
    "陵": "líng",
    "怎": "zěn",
    "骑": "qí",
    "属": "shǔ / zhǔ",
    "管": "guǎn",
    "迁": "qiān",
    "早": "zǎo",
    "客": "kè",
    "仁": "rén",
    "久": "jǐu",
    "监": "jiān / jiàn",
    "深": "shēn",
    "贤": "xián",
    "员": "yuán",
    "尔": "ěr",
    "贵": "guì",
    "星": "xīng",
    "莫": "mò",
    "景": "jǐng",
    "语": "yǔ / yù",
    "车": "chē / jū",
    "堂": "táng",
    "赵": "zhào",
    "收": "shōu",
    "秦": "qín",
    "代": "dài",
    "唐": "táng",
    "集": "jí",
    "飞": "fēi",
    "破": "pò",
    "仙": "xiān",
    "反": "fǎn",
    "近": "jìn",
    "修": "xīu",
    "异": "yì",
    "梁": "liáng",
    "备": "bèi",
    "丁": "dīng",
    "营": "yíng",
    "曾": "céng / zēng",
    "志": "zhì",
    "果": "guǒ",
    "焉": "yān",
    "院": "yuàn",
    "空": "kōng / kòng",
    "夏": "xià",
    "华": "huá / huà",
    "火": "huǒ",
    "全": "quán",
    "急": "jí",
    "临": "lín",
    "样": "yàng",
    "田": "tián",
    "忽": "hū",
    "参": "cān / shēn",
    "永": "yǒng",
    "岂": "qǐ",
    "终": "zhōng",
    "止": "zhǐ",
    "每": "měi",
    "易": "yì",
    "忙": "máng",
    "恩": "ēn",
    "率": "lù: / shuài / lv",
    "辞": "cí",
    "利": "lì",
    "点": "diǎn",
    "谢": "xiè",
    "容": "róng",
    "除": "chú",
    "历": "lì",
    "致": "zhì",
    "晋": "jìn",
    "拿": "ná",
    "败": "bài",
    "征": "zhēng",
    "伯": "bó",
    "胜": "shēng / shèng",
    "妻": "qī / qì",
    "承": "chéng",
    "庙": "miào",
    "仪": "yí",
    "指": "zhǐ",
    "接": "jiē",
    "凡": "fán",
    "兼": "jiān",
    "阴": "yīn",
    "怀": "huái",
    "表": "biǎo",
    "倒": "dǎo / dào",
    "遇": "yù",
    "徐": "xú",
    "满": "mǎn",
    "执": "zhí",
    "密": "mì",
    "红": "hóng",
    "庆": "qìng",
    "授": "shòu",
    "须": "xū",
    "耳": "ěr",
    "恐": "kǒng",
    "济": "jì",
    "土": "tǔ",
    "幸": "xìng",
    "犯": "fàn",
    "游": "yóu",
    "督": "dū",
    "惊": "jīng",
    "船": "chuán",
    "丞": "chéng",
    "召": "shào / zhào",
    "害": "hài",
    "散": "sǎn / sàn",
    "免": "miǎn",
    "福": "fú",
    "攻": "gōng",
    "木": "mù",
    "尉": "wèi",
    "讨": "tǎo",
    "性": "xìng",
    "化": "huà",
    "号": "háo / hào",
    "贾": "gǔ / jiǎ",
    "愿": "yuàn",
    "申": "shēn",
    "良": "liáng",
    "俱": "jū / jù",
    "觉": "jiào / jué",
    "乘": "chéng",
    "廷": "tíng",
    "舍": "shě / shè",
    "干": "gān / gàn",
    "抚": "fǔ",
    "落": "là / luò",
    "候": "hòu",
    "美": "měi",
    "按": "àn",
    "轻": "qīng",
    "顺": "shùn",
    "胡": "hú",
    "徒": "tú",
    "记": "jì",
    "犹": "yóu",
    "什": "shén / shí",
    "献": "xiàn",
    "谁": "shéi / shuí",
    "依": "yī",
    "退": "tuì",
    "谋": "móu",
    "职": "zhí",
    "雨": "yǔ",
    "玄": "xuán",
    "目": "mù",
    "独": "dú",
    "帅": "shuài",
    "郑": "zhèng",
    "步": "bù",
    "姑": "gū",
    "尝": "cháng",
    "提": "dī / tí",
    "罗": "luō / luó",
    "竟": "jìng",
    "爱": "ài",
    "素": "sù",
    "辛": "xīn",
    "绝": "jué",
    "眼": "yǎn",
    "变": "biàn",
    "延": "yán",
    "比": "bǐ / bì",
    "强": "qiáng",
    "品": "pǐn",
    "汝": "rǔ",
    "英": "yīng",
    "灵": "líng",
    "校": "jiào / xiào",
    "毕": "bì",
    "追": "zhuī",
    "答": "dā / dá",
    "辰": "chén",
    "设": "shè",
    "谷": "gǔ / yù",
    "惟": "wéi",
    "威": "wēi",
    "哥": "gē",
    "迎": "yíng",
    "击": "jī",
    "室": "shì",
    "昌": "chāng",
    "益": "yì",
    "极": "jí",
    "亡": "wáng",
    "怒": "nù",
    "权": "quán",
    "伏": "fú",
    "仍": "réng",
    "敬": "jìng",
    "推": "tuī",
    "商": "shāng",
    "骸": "hái",
    "救": "jìu",
    "升": "shēng",
    "副": "fù",
    "图": "tú",
    "疑": "yí",
    "约": "yāo / yuē",
    "察": "chá",
    "僧": "sēng",
    "恶": "ě / è / wù",
    "虎": "hǔ",
    "细": "xì",
    "登": "dēng",
    "业": "yè",
    "梦": "mèng",
    "统": "tǒng",
    "刑": "xíng",
    "似": "sì",
    "固": "gù",
    "阿": "ā / à / a / ē",
    "运": "yùn",
    "视": "shì",
    "凤": "fèng",
    "布": "bù",
    "淮": "huái",
    "音": "yīn",
    "精": "jīng",
    "寿": "shòu",
    "楼": "lóu",
    "乡": "xiāng",
    "楚": "chǔ",
    "牛": "níu",
    "达": "dá",
    "草": "cǎo",
    "略": "luè",
    "尊": "zūn",
    "离": "lí",
    "据": "jū / jù",
    "乙": "yǐ",
    "朔": "shuò",
    "苦": "kǔ",
    "共": "gòng",
    "列": "liè",
    "疾": "jí",
    "午": "wǔ",
    "群": "qún",
    "断": "duàn",
    "川": "chuān",
    "曹": "cáo",
    "持": "chí",
    "赏": "shǎng",
    "昭": "zhāo",
    "嘉": "jiā",
    "陛": "bì",
    "奇": "jī / qí",
    "叔": "shū",
    "射": "shè",
    "招": "zhāo",
    "特": "té / tè",
    "隐": "yǐn",
    "旨": "zhǐ",
    "顾": "gù",
    "肯": "kěn",
    "克": "kè",
    "句": "jù",
    "疏": "shū",
    "饮": "yǐn",
    "快": "kuài",
    "奔": "bēn / bèn",
    "盖": "gài / gě",
    "湖": "hú",
    "曲": "qū / qǔ",
    "私": "sī",
    "体": "tǐ",
    "晚": "wǎn",
    "祭": "jì / zhài",
    "康": "kāng",
    "巡": "xún",
    "势": "shì",
    "暗": "àn",
    "伤": "shāng",
    "禁": "jīn / jìn",
    "怕": "pà",
    "呢": "ne / ní",
    "纳": "nà",
    "苏": "sū",
    "欢": "huān",
    "仆": "pū / pú",
    "珠": "zhū",
    "结": "jiē / jié",
    "越": "yuè",
    "休": "xīu",
    "呼": "hū",
    "刻": "kè",
    "丑": "chǒu",
    "念": "niàn",
    "庚": "gēng",
    "写": "xiě",
    "工": "gōng",
    "孔": "kǒng",
    "微": "wēi",
    "燕": "yān / yàn",
    "让": "ràng",
    "庄": "zhuāng",
    "剑": "jiàn",
    "般": "bān",
    "彼": "bǐ",
    "友": "yǒu",
    "斩": "zhǎn",
    "选": "xuǎn",
    "息": "xī",
    "婆": "pó",
    "怪": "guài",
    "寺": "sì",
    "韩": "hán",
    "仲": "zhòng",
    "壬": "rén",
    "哭": "kū",
    "双": "shuāng",
    "录": "lù",
    "禄": "lù",
    "妹": "mèi",
    "照": "zhào",
    "崇": "chóng",
    "吉": "jí",
    "严": "yán",
    "希": "xī",
    "著": "zhù / zhe",
    "盛": "chéng / shèng",
    "象": "xiàng",
    "条": "tiáo",
    "厚": "hòu",
    "丹": "dān",
    "丙": "bǐng",
    "隆": "lōng / lóng",
    "养": "yǎng",
    "哉": "zāi",
    "丈": "zhàng",
    "废": "fèi",
    "宰": "zǎi",
    "期": "qī",
    "刀": "dāo",
    "闲": "xián",
    "考": "kǎo",
    "阁": "gé",
    "鼓": "gǔ",
    "戊": "wù",
    "富": "fù",
    "宿": "sù / xǐu / xìu",
    "纪": "jì",
    "造": "zào",
    "算": "suàn",
    "敌": "dí",
    "试": "shì",
    "歌": "gē / ge1ge",
    "器": "qì",
    "鲁": "lǔ",
    "铁": "tiě",
    "蒙": "mēng / méng / měng",
    "围": "wéi",
    "雄": "xióng",
    "鬼": "guǐ",
    "决": "jué",
    "调": "diào / tiáo",
    "掌": "zhǎng",
    "班": "bān",
    "驾": "jià",
    "奴": "nú",
    "爵": "jué",
    "馀": "yú",
    "务": "wù",
    "秀": "xìu",
    "柳": "lǐu",
    "虚": "xū",
    "识": "shí / zhì",
    "丧": "sāng / sàng",
    "贞": "zhēn",
    "兰": "lán",
    "诛": "zhū",
    "荣": "róng",
    "沙": "shā",
    "寅": "yín",
    "累": "léi / lěi / lèi",
    "完": "wán",
    "树": "shù",
    "端": "duān",
    "典": "diǎn",
    "癸": "guǐ",
    "盗": "dào",
    "俊": "nan",
    "获": "huò",
    "巳": "sì",
    "阵": "zhèn",
    "博": "bó",
    "诚": "chéng",
    "末": "mò",
    "假": "jiǎ / jià",
    "系": "xì",
    "形": "xíng",
    "载": "zǎi / zài",
    "继": "jì",
    "冬": "dōng",
    "扬": "yáng",
    "显": "xiǎn",
    "寇": "kòu",
    "场": "chǎng",
    "唬": "hǔ",
    "斗": "dǒu / dòu",
    "雪": "xuě",
    "施": "shī",
    "悉": "xī",
    "感": "gǎn",
    "赠": "zèng",
    "劳": "láo",
    "酉": "yǒu",
    "卯": "mǎo",
    "讲": "jiǎng",
    "番": "fān / pān",
    "移": "yí",
    "藏": "cáng / zàng",
    "遗": "yí",
    "劝": "quàn",
    "赤": "chì",
    "具": "jù",
    "嗣": "sì",
    "朕": "zhèn",
    "陆": "lìu / lù",
    "谏": "jiàn",
    "忧": "yōu",
    "种": "zhǒng / zhòng",
    "奸": "jiān",
    "存": "cún",
    "晓": "xiǎo",
    "饭": "fàn",
    "缘": "yuán",
    "策": "cè",
    "男": "nán",
    "补": "bǔ",
    "机": "jī",
    "充": "chōng",
    "护": "hù",
    "黑": "hēi",
    "紫": "zǐ",
    "案": "àn",
    "恭": "gōng",
    "索": "suǒ",
    "现": "xiàn",
    "冠": "guān / guàn",
    "泰": "tài",
    "画": "huà",
    "贡": "gòng",
    "萧": "xiāo",
    "屯": "tún / zhūn",
    "术": "shù / zhú",
    "亥": "hài",
    "芳": "fāng",
    "勿": "wù",
    "乞": "qǐ",
    "佛": "fó / fú",
    "杜": "dù",
    "洪": "hóng",
    "单": "chán / dān / shàn",
    "袭": "xí",
    "赶": "gǎn",
    "减": "jiǎn",
    "积": "jī",
    "咸": "xián",
    "件": "jiàn",
    "妖": "yāo",
    "薄": "bó / bò / báo",
    "岳": "yuè",
    "药": "yào",
    "谕": "yù",
    "切": "qiē / qiè",
    "伐": "fá",
    "叹": "tàn",
    "刚": "gāng",
    "状": "zhuàng",
    "允": "yǔn",
    "园": "yuán",
    "惠": "huì",
    "戌": "xū",
    "争": "zhēng",
    "朱": "zhū",
    "办": "bàn",
    "松": "sōng",
    "尺": "chǐ",
    "旁": "páng",
    "邑": "yì",
    "寒": "hán",
    "读": "dòu / dú",
    "颜": "yán",
    "吕": "lǔ: / lv",
    "荆": "jīng",
    "印": "yìn",
    "钟": "zhōng",
    "赴": "fù",
    "范": "fàn",
    "律": "lù: / lv",
    "狱": "yù",
    "静": "jìng",
    "邪": "xié",
    "防": "fáng",
    "庶": "shù",
    "睡": "shuì",
    "雷": "léi",
    "恨": "hèn",
    "认": "rèn",
    "词": "cí",
    "投": "tóu",
    "赞": "zàn",
    "况": "kuàng",
    "财": "cái",
    "野": "yě",
    "逃": "táo",
    "旗": "qí",
    "拔": "bá",
    "惧": "jù",
    "席": "xí",
    "辅": "fǔ",
    "市": "shì",
    "孟": "mèng",
    "茶": "chá",
    "奶": "nǎi",
    "怨": "yuàn",
    "冲": "chōng / chòng",
    "屋": "wū",
    "脱": "tuō",
    "背": "bēi / bèi",
    "买": "nan",
    "费": "fèi",
    "宾": "bīn",
    "孤": "gū",
    "洛": "luò",
    "渐": "jiān / jiàn",
    "党": "dǎng",
    "判": "pàn",
    "夷": "yí",
    "亮": "liàng",
    "童": "tóng",
    "附": "fù",
    "负": "fù",
    "乌": "wū",
    "梅": "méi",
    "役": "yì",
    "辽": "liáo",
    "粮": "liáng",
    "托": "tuō",
    "俗": "sú",
    "撰": "zhuàn",
    "赋": "fù",
    "贺": "hè",
    "勇": "yǒng",
    "量": "liáng / liàng",
    "祀": "sì",
    "穿": "chuān",
    "迹": "jī / jì",
    "笔": "bǐ",
    "敕": "chì",
    "检": "jiǎn",
    "幽": "yōu",
    "跟": "gēn",
    "脚": "jiǎo / jué",
    "专": "zhuān",
    "郭": "guō",
    "妃": "fēi",
    "弃": "qì",
    "增": "zēng",
    "横": "héng / hèng",
    "叶": "yè",
    "折": "shé / zhé",
    "灾": "zāi",
    "付": "fù",
    "温": "wēn",
    "角": "jiǎo / jué",
    "昔": "xī",
    "程": "chéng",
    "鱼": "yú",
    "最": "zuì",
    "患": "huàn",
    "弘": "hóng",
    "沈": "chén / shěn",
    "庭": "tíng",
    "舞": "wǔ",
    "烟": "yān",
    "挥": "huī",
    "祸": "huò",
    "卢": "lú",
    "逆": "nì",
    "傅": "fù",
    "薛": "xuē",
    "悦": "yuè",
    "乾": "gān / qián",
    "资": "zī",
    "崔": "cuī",
    "床": "chuáng",
    "停": "tíng",
    "垂": "chuí",
    "洞": "dòng",
    "杂": "zá",
    "灭": "miè",
    "很": "hěn",
    "喝": "hē / hè",
    "消": "xiāo",
    "准": "zhǔn",
    "支": "zhī",
    "葬": "zàng",
    "弄": "lòng / nòng",
    "隶": "lì",
    "斯": "sī",
    "妾": "qiè",
    "罚": "fá",
    "露": "lù / lòu",
    "该": "gāi",
    "锦": "jǐn",
    "灯": "dēng",
    "活": "huó",
    "襄": "xiāng",
    "格": "gé",
    "责": "zé",
    "族": "zú",
    "尤": "yóu",
    "帐": "zhàng",
    "聚": "jù",
    "奈": "nài",
    "枢": "shū",
    "丽": "lí / lì",
    "谥": "shì",
    "尹": "yǐn",
    "妙": "miào",
    "纵": "zōng / zòng",
    "采": "cǎi / cài",
    "雅": "yǎ",
    "肃": "sù",
    "夺": "duó",
    "蜀": "shǔ",
    "舟": "zhōu",
    "馆": "guǎn",
    "避": "bì",
    "鸣": "míng",
    "阙": "quē / què",
    "陷": "xiàn",
    "唯": "wéi / wěi",
    "牙": "yá",
    "符": "fú",
    "盘": "pán",
    "智": "zhì",
    "丰": "fēng",
    "危": "wēi",
    "震": "zhèn",
    "亭": "tíng",
    "释": "shì",
    "类": "lèi",
    "彦": "yàn",
    "徙": "xǐ",
    "包": "bāo",
    "紧": "jǐn",
    "戒": "jiè",
    "卖": "nan",
    "访": "fǎng",
    "穷": "qióng",
    "骨": "gǔ",
    "简": "jiǎn",
    "谈": "tán",
    "勒": "lè / lēi",
    "籍": "jí",
    "盐": "yán",
    "助": "zhù",
    "泉": "quán",
    "供": "gōng / gòng",
    "桓": "huán",
    "哀": "āi",
    "委": "wēi / wěi",
    "赦": "shè",
    "季": "jì",
    "借": "jiè",
    "荐": "jiàn",
    "颇": "pō",
    "店": "diàn",
    "翰": "hàn",
    "速": "sù",
    "遍": "biàn",
    "杯": "bēi",
    "溃": "kuì",
    "甫": "fǔ",
    "料": "liào",
    "贫": "pín",
    "池": "chí",
    "诣": "yì",
    "宴": "yàn",
    "迟": "chí",
    "匹": "pī / pǐ",
    "耍": "shuǎ",
    "像": "xiàng",
    "绍": "shào",
    "寨": "zhài",
    "忘": "wàng",
    "殷": "yān / yīn / yǐn",
    "泪": "lèi",
    "翠": "cuì",
    "段": "duàn",
    "凶": "xiōng",
    "坏": "huài",
    "珍": "zhēn",
    "误": "wù",
    "汤": "tāng",
    "肉": "ròu",
    "唤": "huàn",
    "雍": "yōng",
    "狄": "dí",
    "巴": "bā",
    "蔡": "cài",
    "科": "kē",
    "适": "shì",
    "习": "xí",
    "源": "yuán",
    "座": "zuò",
    "替": "tì",
    "穆": "mù",
    "某": "mǒu",
    "示": "shì",
    "境": "jìng",
    "虞": "yú",
    "枝": "zhī",
    "竹": "zhú",
    "慢": "màn",
    "祥": "xiáng",
    "旦": "dàn",
    "郊": "jiāo",
    "题": "tí",
    "诉": "sù",
    "塞": "sāi / sài / sè",
    "拢": "lǒng",
    "醉": "zuì",
    "配": "pèi",
    "溪": "qī / xī",
    "篇": "piān",
    "泽": "zé",
    "底": "de / dǐ",
    "界": "jiè",
    "忍": "rěn",
    "径": "jìng",
    "岸": "àn",
    "妈": "mā",
    "启": "qǐ",
    "衙": "yá",
    "桥": "qiáo",
    "儒": "rú",
    "熙": "xī",
    "稍": "shāo",
    "壁": "bì",
    "质": "zhì",
    "环": "huán",
    "米": "mǐ",
    "根": "gēn",
    "农": "nóng",
    "扶": "fú",
    "坚": "jiān",
    "宽": "kuān",
    "村": "cūn",
    "幼": "yòu",
    "页": "yè",
    "荒": "huāng",
    "彩": "cǎi",
    "骂": "mà",
    "烧": "shāo",
    "叛": "pàn",
    "渡": "dù",
    "戏": "xì",
    "佐": "zuǒ",
    "逢": "féng",
    "脸": "liǎn",
    "夕": "xī / xì",
    "丘": "qīu",
    "虑": "lù: / lv",
    "探": "tàn",
    "署": "shǔ",
    "顿": "dùn",
    "井": "jǐng",
    "宪": "xiàn",
    "仇": "chóu / qíu",
    "羽": "yǔ",
    "巧": "qiǎo",
    "库": "kù",
    "摇": "yáo",
    "阶": "jiē",
    "祝": "zhù",
    "仓": "cāng",
    "吹": "chuī",
    "甘": "gān",
    "仕": "shì",
    "占": "zhān / zhàn",
    "振": "zhèn",
    "浮": "fú",
    "毛": "máo",
    "惜": "xī",
    "痛": "tòng",
    "冯": "féng",
    "戎": "róng",
    "逐": "zhú",
    "貌": "mào",
    "寸": "cùn",
    "烈": "liè",
    "闹": "nào",
    "莲": "lián",
    "详": "xiáng",
    "皮": "pí",
    "钦": "qīn",
    "豫": "yù",
    "韦": "wéi",
    "血": "xiě / xuè",
    "顷": "qǐng",
    "限": "xiàn",
    "换": "huàn",
    "突": "tū",
    "预": "yù",
    "屈": "qū",
    "蛮": "mán",
    "饥": "jī",
    "覆": "fù",
    "抱": "bào",
    "衡": "héng",
    "寄": "jì",
    "偏": "piān",
    "宅": "zhái",
    "眉": "méi",
    "戴": "dài",
    "整": "zhěng",
    "捕": "bǔ",
    "孩": "hái",
    "昨": "zuó",
    "贯": "guàn",
    "社": "shè",
    "硃": "zhū",
    "遥": "yáo",
    "悲": "bēi",
    "跪": "guì",
    "翁": "wēng",
    "瑞": "ruì",
    "桑": "sāng",
    "辄": "zhé",
    "局": "jú",
    "昏": "hūn",
    "裕": "yù",
    "勋": "xūn",
    "拾": "shí",
    "禀": "bǐng",
    "寡": "guǎ",
    "凉": "liáng",
    "董": "dǒng",
    "羊": "yáng",
    "例": "lì",
    "街": "jiē",
    "廉": "lián",
    "耶": "yē",
    "操": "cāo",
    "怜": "lián",
    "否": "fǒu / pǐ",
    "鸟": "niǎo",
    "侵": "qīn",
    "徽": "huī",
    "虏": "lǔ",
    "响": "xiǎng",
    "吐": "tǔ / tù",
    "牵": "qiān",
    "谒": "yè",
    "审": "shěn",
    "擒": "qín",
    "烦": "fán",
    "残": "cán",
    "哈": "hā / hǎ",
    "尸": "shī",
    "岭": "lǐng",
    "影": "yǐng",
    "魂": "hún",
    "桂": "guì",
    "猛": "měng",
    "窃": "qiè",
    "站": "zhàn",
    "俺": "ǎn",
    "勤": "qín",
    "契": "qì",
    "援": "yuán",
    "兮": "xī",
    "兆": "zhào",
    "桃": "táo",
    "辈": "bèi",
    "蕃": "fán / fān",
    "暴": "bào",
    "壮": "zhuàng",
    "恕": "shù",
    "惑": "huò",
    "陕": "shǎn / shǎn",
    "她": "tā",
    "绿": "lù: / lv",
    "杖": "zhàng",
    "枪": "qiāng",
    "畏": "wèi",
    "冷": "lěng",
    "牧": "mù",
    "丝": "sī",
    "耐": "nài",
    "愈": "yù",
    "冤": "yuān",
    "轮": "lún",
    "述": "shù",
    "愁": "chóu",
    "尘": "chén",
    "愚": "yú",
    "险": "xiǎn",
    "抵": "dǐ",
    "祠": "cí",
    "谦": "qiān",
    "霞": "xiá",
    "丫": "yā",
    "弥": "mí",
    "轿": "jiào",
    "弱": "ruò",
    "翼": "yì",
    "错": "cuò",
    "慰": "wèi",
    "辟": "bì / pì",
    "圆": "yuán",
    "短": "duǎn",
    "违": "wéi",
    "靖": "jìng",
    "宠": "chǒng",
    "潜": "qián",
    "哩": "lī / lǐ / li",
    "哪": "nǎ / na / něi",
    "额": "é",
    "热": "rè",
    "尾": "wěi",
    "训": "xùn",
    "茂": "mào",
    "效": "xiào",
    "斋": "zhāi",
    "谨": "jǐn",
    "箭": "jiàn",
    "洗": "xǐ",
    "闭": "bì",
    "浑": "hún",
    "超": "chāo",
    "醒": "xǐng",
    "舅": "jìu",
    "驰": "chí",
    "遭": "zāo",
    "佳": "jiā",
    "咐": "fù",
    "找": "zhǎo",
    "沉": "chén",
    "逼": "bī",
    "掠": "luè / luě",
    "摆": "bǎi",
    "鸿": "hóng",
    "鲜": "xiān / xiǎn",
    "队": "duì",
    "税": "shuì",
    "弓": "gōng",
    "湘": "xiāng",
    "宇": "yǔ",
    "仗": "zhàng",
    "邓": "dèng",
    "纸": "zhǐ",
    "恰": "qià",
    "排": "pái / pǎi",
    "厥": "jué",
    "片": "piān / piàn",
    "择": "zé / zhái",
    "屡": "lǔ: / lv",
    "慈": "cí",
    "仰": "yǎng",
    "旱": "hàn",
    "薨": "hōng",
    "慌": "huāng",
    "浙": "zhè",
    "豪": "háo",
    "崩": "bēng",
    "伦": "lún",
    "医": "yī",
    "擢": "zhuó",
    "级": "jí",
    "拒": "jù",
    "产": "chǎn",
    "泣": "qì",
    "挂": "guà",
    "洋": "yáng",
    "净": "jìng",
    "歇": "xiē",
    "贪": "tān",
    "碧": "bì",
    "损": "sǔn",
    "兀": "wù / wū",
    "装": "zhuāng",
    "慕": "mù",
    "赖": "lài",
    "淫": "yín",
    "瞧": "qiáo",
    "厮": "sī",
    "秘": "mì",
    "戚": "qī",
    "袁": "yuán",
    "均": "nan",
    "簿": "bù",
    "低": "dī",
    "墙": "qiáng",
    "侄": "zhí",
    "陶": "táo",
    "跑": "pǎo",
    "稽": "jī / qǐ",
    "团": "tuán",
    "波": "bō",
    "吩": "fēn",
    "舆": "yú",
    "材": "cái",
    "邻": "lín",
    "贱": "jiàn",
    "翻": "fān",
    "遵": "zūn",
    "卧": "wò",
    "册": "cè",
    "卜": "bo / bǔ",
    "嫁": "jià",
    "冀": "jì",
    "凭": "píng",
    "窗": "chuāng",
    "验": "yàn",
    "堪": "kān",
    "慎": "shèn",
    "筑": "zhú / zhù",
    "叙": "xù",
    "忌": "jì",
    "裴": "péi",
    "绣": "xìu",
    "困": "kǔn / kùn",
    "唱": "chàng",
    "鼎": "dǐng",
    "寝": "qǐn",
    "苟": "gǒu",
    "饰": "shì",
    "导": "dǎo",
    "爹": "diē",
    "捉": "zhuō",
    "喊": "hǎn",
    "铜": "tóng",
    "规": "guī",
    "值": "zhí",
    "货": "huò",
    "钗": "chāi",
    "隋": "suí",
    "偷": "tōu",
    "顶": "dǐng",
    "禅": "chán / shàn",
    "狐": "hú",
    "俄": "é",
    "浚": "xùn",
    "担": "dān / dàn",
    "锡": "xí / xī",
    "韵": "yùn",
    "鸡": "jī",
    "帛": "bó",
    "查": "chá / zhā",
    "跳": "tiào",
    "练": "liàn",
    "纷": "fēn",
    "掩": "yǎn",
    "彭": "péng",
    "倚": "yǐ",
    "浪": "làng",
    "陪": "péi",
    "殊": "shū",
    "拥": "yōng",
    "倘": "tǎng",
    "朋": "péng",
    "革": "gé",
    "悄": "qiǎo / qiāo",
    "拉": "lā",
    "驻": "zhù",
    "亏": "kuī",
    "汗": "hàn",
    "咱": "zá / zán",
    "祐": "yòu",
    "缓": "huǎn",
    "於": "yū / yú",
    "疲": "pí",
    "熟": "shú",
    "派": "pài",
    "弦": "xián",
    "姚": "yáo",
    "予": "yú / yǔ",
    "毁": "huǐ",
    "际": "jì",
    "惺": "xīng",
    "悟": "wù",
    "盈": "yíng",
    "式": "shì",
    "健": "jiàn",
    "叩": "kòu",
    "输": "shū",
    "模": "mó",
    "厅": "tīng",
    "鹿": "lù",
    "玩": "wán / wàn",
    "夹": "jiā / jiá",
    "冰": "bīng",
    "庐": "lú",
    "劫": "jié",
    "焚": "fén",
    "腹": "fù",
    "俟": "sì",
    "伊": "yī",
    "昼": "zhòu",
    "享": "xiǎng",
    "樱": "yīng",
    "辏": "còu",
    "嘴": "zuǐ",
    "婢": "bì",
    "撸": "lū",
    "究": "jīu",
    "倾": "qīng",
    "倍": "bèi",
    "葛": "gé / gě",
    "尼": "ní",
    "维": "wéi",
    "弼": "bì",
    "旋": "xuán / xuàn",
    "迷": "mí",
    "含": "hán",
    "琼": "qióng",
    "毒": "dú",
    "舜": "shùn",
    "吟": "yín",
    "优": "yōu",
    "序": "xù",
    "腰": "yāo",
    "蒋": "jiǎng",
    "戍": "shù",
    "晕": "yūn / yùn",
    "侧": "cè / zhāi",
    "苍": "cāng",
    "邦": "bāng",
    "隔": "gé",
    "牌": "pái",
    "娶": "qǔ",
    "狗": "gǒu",
    "普": "pǔ",
    "锋": "fēng",
    "荡": "dàng",
    "劾": "hé",
    "鹤": "hè",
    "它": "tā",
    "津": "jīn",
    "嫂": "sǎo",
    "姨": "yí",
    "款": "kuǎn",
    "菜": "cài",
    "递": "dì",
    "卑": "bēi",
    "牢": "láo",
    "稷": "jì",
    "饶": "ráo",
    "苑": "yuàn",
    "板": "bǎn",
    "弊": "bì",
    "囚": "qíu",
    "妄": "wàng",
    "杰": "jié",
    "悔": "huǐ",
    "铺": "pū / pù",
    "扇": "shān / shàn",
    "坛": "tán",
    "毋": "wú",
    "娇": "jiāo",
    "束": "shù",
    "抬": "tái",
    "渊": "yuān",
    "暮": "mù",
    "皋": "gāo",
    "阻": "zǔ",
    "衰": "cuī / shuāi",
    "价": "jià / jie",
    "途": "tú",
    "贰": "èr",
    "柱": "zhù",
    "姊": "zǐ",
    "琴": "qín",
    "匡": "kuāng",
    "味": "wèi",
    "辉": "huī",
    "婚": "hūn",
    "暂": "zàn",
    "霸": "bà",
    "冢": "zhǒng",
    "伪": "wěi",
    "仔": "zī / zǐ / zǎi",
    "项": "xiàng",
    "趣": "qù",
    "弗": "fú",
    "袖": "xìu",
    "麻": "má",
    "展": "zhǎn",
    "辨": "biàn",
    "介": "jiè",
    "尧": "yáo",
    "编": "biān",
    "趋": "qū",
    "聪": "cōng",
    "块": "kuāi / kuài",
    "距": "jù",
    "扰": "rǎo",
    "屏": "bǐng / píng",
    "驱": "qū",
    "腾": "téng",
    "辱": "rǔ",
    "睿": "ruì",
    "舒": "shū",
    "泄": "xiè",
    "秩": "zhì",
    "庸": "yōng",
    "押": "yā",
    "盟": "méng",
    "烛": "zhú",
    "艺": "yì",
    "岩": "yán",
    "偶": "ǒu",
    "缺": "quē",
    "肆": "sì",
    "证": "zhèng",
    "僚": "liáo",
    "玻": "bō",
    "续": "xù",
    "阅": "yuè",
    "裁": "cái",
    "纲": "gāng",
    "履": "lǔ: / lv",
    "敏": "mǐn",
    "厉": "lì",
    "庵": "ān",
    "黎": "lí",
    "窦": "dòu",
    "荷": "hé / hè",
    "敝": "bì",
    "鉴": "jiàn",
    "墨": "mò",
    "狂": "kuáng",
    "逾": "yú",
    "基": "jī",
    "币": "bì",
    "巾": "jīn",
    "纯": "chún",
    "欺": "qī",
    "览": "lǎn",
    "敦": "dūn",
    "胆": "dǎn",
    "嫌": "xián",
    "帘": "lián",
    "涂": "tú",
    "黛": "dài",
    "遁": "dùn",
    "兹": "zī",
    "旅": "lǔ: / lv",
    "弹": "dàn / tán",
    "柴": "chái",
    "繁": "fán",
    "蒲": "pú",
    "循": "xún",
    "协": "xié",
    "躬": "gōng",
    "帖": "tiē / tiě / tiè",
    "衔": "xián",
    "焦": "jiāo",
    "呈": "chéng",
    "悬": "xuán",
    "镜": "jìng",
    "贝": "bèi",
    "羞": "xīu",
    "桌": "zhuō",
    "吊": "diào",
    "冒": "mào",
    "钞": "chāo",
    "衍": "yǎn",
    "邀": "yāo",
    "浦": "pǔ",
    "俭": "jiǎn",
    "逸": "yì",
    "颍": "yǐng",
    "粗": "cū",
    "潘": "pān",
    "课": "kè",
    "粉": "fěn",
    "淳": "chún",
    "巨": "jù",
    "聘": "pìn",
    "矢": "shǐ",
    "墓": "mù",
    "蛇": "shé",
    "默": "mò",
    "贬": "biǎn",
    "涉": "shè",
    "割": "gē",
    "缄": "jiān",
    "痴": "chī",
    "兽": "shòu",
    "驿": "yì",
    "锁": "suǒ",
    "晁": "cháo",
    "浅": "jiān / qiǎn",
    "呀": "ya / yā",
    "妆": "zhuāng",
    "宦": "huàn",
    "拨": "bō",
    "鸾": "luán",
    "勉": "miǎn",
    "晏": "yàn",
    "另": "lìng",
    "恢": "huī",
    "蝗": "huáng",
    "灰": "huī",
    "敛": "liǎn",
    "妨": "fáng",
    "辩": "biàn",
    "坊": "fāng",
    "拟": "nǐ",
    "媳": "xí",
    "龟": "guī",
    "婿": "xù",
    "浩": "hào",
    "佩": "pèi",
    "拱": "gǒng",
    "朗": "lǎng",
    "戮": "lù",
    "诵": "sòng",
    "粟": "sù",
    "绛": "jiàng",
    "捷": "jié",
    "荩": "jìn",
    "诈": "zhà",
    "霜": "shuāng",
    "懿": "yì",
    "晨": "chén",
    "毫": "háo",
    "渠": "qú",
    "柔": "róu",
    "羌": "qiāng",
    "闷": "mēn / mèn",
    "逊": "xùn",
    "狼": "láng",
    "搭": "dā",
    "姜": "jiāng",
    "矗": "chù",
    "猎": "liè",
    "鞭": "biān",
    "勾": "gōu / gòu",
    "耕": "gēng",
    "茫": "máng",
    "吗": "mǎ / ma",
    "揖": "yī",
    "标": "biāo",
    "莽": "mǎng",
    "胤": "yìn",
    "斜": "xié",
    "诱": "yòu",
    "激": "jī",
    "募": "mù",
    "斤": "jīn",
    "轩": "xuān",
    "催": "cuī",
    "吓": "xià",
    "麟": "lín",
    "萨": "sà",
    "抢": "qiāng / qiǎng",
    "酌": "zhuó",
    "嵩": "sōng",
    "苗": "miáo",
    "棺": "guān",
    "拍": "pāi",
    "抑": "yì",
    "伺": "cì / sì",
    "携": "xié",
    "绪": "xù",
    "陇": "lǒng",
    "姬": "jī",
    "较": "jiào",
    "姻": "yīn",
    "欣": "xīn",
    "讫": "qì",
    "澄": "chéng / dèng",
    "伴": "bàn",
    "齿": "chǐ",
    "裳": "cháng / shang",
    "淌": "tǎng",
    "禹": "yǔ",
    "汴": "biàn",
    "埋": "mán",
    "蔽": "bì",
    "彪": "biāo",
    "抄": "chāo",
    "漏": "lòu",
    "扯": "chě",
    "罕": "hǎn",
    "笃": "dǔ",
    "挑": "tiāo / tiǎo",
    "租": "zū",
    "筵": "yán",
    "誓": "shì",
    "酰": "xiān",
    "恼": "nǎo",
    "眷": "juàn",
    "返": "fǎn",
    "倪": "ní",
    "枉": "wǎng",
    "绕": "rào",
    "沿": "yán / yàn",
    "摄": "shè",
    "媒": "méi",
    "囊": "náng",
    "擅": "shàn",
    "慧": "huì",
    "拘": "jū",
    "艘": "sāo / sōu",
    "旬": "xún",
    "泥": "ní / nì",
    "芝": "zhī",
    "创": "chuāng / chuàng",
    "凌": "líng",
    "袍": "páo",
    "伸": "shēn",
    "诰": "gào",
    "奋": "fèn",
    "坠": "zhuì",
    "庞": "páng",
    "畜": "chù / xù",
    "伍": "wǔ",
    "靡": "mí / mǐ",
    "融": "róng",
    "添": "tiān",
    "削": "xiāo / xuē",
    "恃": "shì",
    "零": "líng",
    "郁": "yù",
    "昆": "kūn",
    "谅": "liàng",
    "堤": "dī",
    "峰": "fēng",
    "撞": "zhuàng",
    "架": "jià",
    "伞": "sǎn",
    "稀": "xī",
    "澹": "dàn / tán",
    "绳": "shéng",
    "帮": "bāng",
    "铮": "zhēng",
    "耻": "chǐ",
    "披": "pī",
    "扫": "sǎo / sào",
    "呆": "dāi",
    "剩": "shèng",
    "厌": "yàn",
    "电": "diàn",
    "枕": "zhěn",
    "魁": "kuí",
    "骄": "jiāo",
    "豆": "dòu",
    "混": "hún / hùn",
    "塘": "táng",
    "飘": "piāo",
    "恤": "xù",
    "搜": "sōu",
    "股": "gǔ",
    "宏": "hóng",
    "怠": "dài",
    "梗": "gěng",
    "杭": "háng",
    "寓": "yù",
    "伙": "huǒ",
    "馈": "kuì",
    "啊": "ā / á / ǎ / à",
    "跃": "yuè",
    "昂": "áng",
    "蓝": "la / lán",
    "褚": "chǔ",
    "荽": "suī",
    "巢": "cháo",
    "瑶": "yáo",
    "彻": "chè",
    "乏": "fá",
    "鄙": "bǐ",
    "区": "ōu / qū",
    "爽": "shuǎng",
    "邢": "xíng",
    "碎": "suì",
    "捧": "pěng",
    "钩": "gōu",
    "淡": "dàn",
    "讼": "sòng",
    "抽": "chōu",
    "巫": "wū",
    "鲍": "bào",
    "幕": "mù",
    "锐": "ruì",
    "赛": "sài",
    "绩": "jī / jì",
    "脑": "nǎo",
    "频": "pín",
    "奚": "xī",
    "翔": "xiáng",
    "诬": "wū",
    "奠": "diàn",
    "帽": "mào",
    "肠": "cháng",
    "寂": "jì",
    "瓦": "wǎ",
    "鼻": "bí",
    "诘": "jié",
    "构": "gòu",
    "邵": "shào",
    "轨": "guǐ",
    "禽": "qín",
    "测": "cè",
    "辖": "xiá",
    "抗": "kàng",
    "屠": "tú",
    "匆": "cōng",
    "旌": "jīng",
    "绢": "juàn",
    "趁": "chèn",
    "鳎": "tǎ",
    "隙": "xì",
    "祈": "qí",
    "诺": "nuò",
    "壶": "hú",
    "瓜": "guā",
    "朴": "pò / pǔ",
    "臂": "bì",
    "乔": "qiáo",
    "赈": "zhèn",
    "遽": "jù",
    "恚": "huì",
    "挺": "tǐng",
    "汪": "wāng",
    "植": "zhí",
    "酬": "chóu",
    "笼": "lóng",
    "碗": "wǎn",
    "雁": "yàn",
    "秉": "bǐng",
    "闰": "rùn",
    "匠": "jiàng",
    "凝": "níng",
    "傍": "bāng / bàng",
    "颠": "diān",
    "涕": "tì",
    "祚": "zuò",
    "坟": "fén",
    "央": "yāng",
    "谟": "mó",
    "菩": "pú",
    "炎": "yán",
    "肩": "jiān",
    "愧": "kuì",
    "娥": "é",
    "揭": "jiē",
    "肌": "jī",
    "眨": "zhǎ",
    "佥": "qiān",
    "徵": "zhēng / zhǐ",
    "虔": "qián",
    "毅": "yì",
    "嗟": "jiē / juē",
    "压": "yā / yà",
    "豹": "bào",
    "竭": "jié",
    "网": "wǎng",
    "凑": "còu",
    "媚": "mèi",
    "愤": "fèn",
    "磨": "mó / mò",
    "油": "yóu",
    "咏": "yǒng",
    "谑": "xuè",
    "晃": "huǎng / huàng",
    "瓶": "píng",
    "晦": "huì",
    "掉": "diào",
    "岛": "dǎo",
    "靠": "kào",
    "柏": "bǎi / bò",
    "虫": "chóng",
    "沟": "gōu",
    "润": "rùn",
    "莺": "yīng",
    "纾": "shū",
    "杏": "xìng",
    "籓": "bān",
    "洁": "jié",
    "泊": "bó",
    "肚": "dǔ / dù",
    "迫": "pò",
    "警": "jǐng",
    "黜": "chù",
    "储": "chǔ",
    "铸": "zhù",
    "缚": "fú / fù",
    "俯": "fǔ",
    "渔": "yú",
    "斥": "chì",
    "匈": "xiōng",
    "疆": "jiāng",
    "呵": "ā / hē",
    "埃": "āi",
    "卓": "zhuó",
    "绵": "mián",
    "雾": "wù",
    "洲": "zhōu",
    "螅": "xī",
    "勃": "bó",
    "闪": "shǎn",
    "舌": "shé",
    "暇": "xiá",
    "套": "tào",
    "敖": "áo",
    "泛": "fàn",
    "漕": "cáo",
    "砍": "kǎn",
    "肥": "féi",
    "猿": "yuán",
    "樊": "fán",
    "惨": "cǎn",
    "潮": "cháo",
    "匪": "fěi",
    "猜": "cāi",
    "胸": "xiōng",
    "阎": "yán",
    "扑": "pū",
    "够": "gòu",
    "姿": "zī",
    "邮": "yóu",
    "贴": "tiē",
    "炮": "pào",
    "缠": "chán",
    "啼": "tí",
    "佑": "yòu",
    "躲": "duǒ",
    "垣": "yuán",
    "挹": "yì",
    "偃": "yǎn",
    "纱": "shā",
    "哲": "zhé",
    "汲": "jí",
    "莱": "lái",
    "丢": "dīu",
    "榜": "bǎng",
    "晌": "shǎng",
    "岑": "cén",
    "乖": "guāi",
    "荨": "qián",
    "洌": "liè",
    "颖": "yǐng",
    "阔": "kuò",
    "渭": "wèi",
    "互": "hù",
    "恒": "héng",
    "斧": "fǔ",
    "赫": "hè",
    "讳": "huì",
    "撒": "sā / sǎ",
    "穴": "xué",
    "耀": "yào",
    "惶": "huáng",
    "孰": "shú",
    "彰": "zhāng",
    "晴": "qíng",
    "犬": "quǎn",
    "耸": "sǒng",
    "吧": "bā / ba",
    "恋": "liàn",
    "垒": "lěi",
    "签": "qiān",
    "棍": "gùn",
    "械": "xiè",
    "岐": "qí",
    "峻": "nan",
    "搬": "bān",
    "层": "céng",
    "粒": "lì",
    "骇": "hài",
    "稳": "wěn",
    "摸": "mō / mó",
    "驴": "lú: / lv",
    "蓬": "péng",
    "潭": "tán",
    "炼": "liàn",
    "槐": "huái",
    "亟": "jí / qì",
    "窥": "kuī",
    "宛": "wǎn",
    "臧": "zāng",
    "啥": "shá",
    "育": "yù",
    "亩": "mǔ",
    "艳": "yàn",
    "鸳": "yuān",
    "扎": "zā / zhā / zhá",
    "骁": "xiāo",
    "璧": "bì",
    "妓": "jì",
    "铎": "duó",
    "魔": "mó",
    "熊": "xióng",
    "饷": "xiǎng",
    "跌": "diē",
    "概": "gài",
    "颂": "sòng",
    "逮": "dǎi / dài",
    "胁": "xié",
    "褒": "bāo",
    "龄": "líng",
    "线": "xiàn",
    "赃": "zāng",
    "赂": "lù",
    "窍": "qiào",
    "括": "kuò",
    "塔": "tǎ",
    "勘": "kān",
    "陀": "tuó",
    "惭": "cán",
    "淹": "yān",
    "韶": "sháo",
    "衫": "shān",
    "辕": "yuán",
    "冥": "míng",
    "酥": "sū",
    "飨": "xiǎng",
    "棒": "bàng",
    "竞": "jìng",
    "暖": "nuǎn",
    "诞": "dàn",
    "剿": "chāo / jiǎo",
    "堆": "duī",
    "滋": "zī",
    "逵": "kuí",
    "柄": "bǐng",
    "恍": "huǎng",
    "咎": "jìu",
    "联": "lián",
    "厢": "xiāng",
    "猪": "zhū",
    "拳": "quán",
    "域": "yù",
    "闺": "guī",
    "攀": "pān",
    "绶": "shòu",
    "污": "wū",
    "丛": "cóng",
    "剌": "lá / là",
    "椅": "yǐ",
    "詹": "zhān",
    "後": "hòu",
    "畿": "jī",
    "雕": "diāo",
    "奖": "jiǎng",
    "染": "rǎn",
    "殆": "dài",
    "瞻": "zhān",
    "插": "chā",
    "晖": "huī",
    "遮": "zhē",
    "演": "yǎn",
    "宵": "xiāo",
    "泾": "jīng",
    "秒": "miǎo",
    "璋": "zhāng",
    "绰": "chuò / chāo",
    "刃": "rèn",
    "庇": "bì",
    "映": "yìng",
    "沧": "cāng",
    "询": "xún",
    "幻": "huàn",
    "淑": "shū",
    "软": "ruǎn",
    "弧": "hú",
    "填": "tián",
    "咽": "yān / yàn / yè",
    "溢": "yì",
    "荧": "yíng",
    "敲": "qiāo",
    "滑": "gǔ / huá",
    "浴": "yù",
    "睢": "suī",
    "匿": "nì",
    "偕": "jiē / xié",
    "拦": "lán",
    "滚": "gǔn",
    "仅": "jǐn",
    "侠": "xiá",
    "嘱": "zhǔ",
    "椋": "liáng",
    "吞": "tūn",
    "绥": "suí",
    "灌": "guàn",
    "堡": "bǎo / pù",
    "鳌": "áo",
    "织": "zhī",
    "翟": "dí / zhái",
    "赎": "shú",
    "腿": "tuǐ",
    "伟": "wěi",
    "俸": "fèng",
    "朵": "duǒ",
    "牲": "shēng",
    "睛": "jīng",
    "卦": "guà",
    "扮": "bàn",
    "潞": "lù",
    "埽": "sào",
    "煌": "huáng",
    "羡": "xiàn",
    "豢": "huàn",
    "戈": "gē",
    "雀": "qiāo / qiǎo / què",
    "芦": "lú",
    "哄": "hōng / hǒng / hòng",
    "谐": "xié",
    "麾": "huī",
    "嚷": "rǎng",
    "拂": "fú",
    "敷": "fū",
    "践": "jiàn",
    "欠": "qiàn",
    "昧": "mèi",
    "芬": "fēn",
    "纠": "jīu",
    "怯": "qiè",
    "梢": "shāo",
    "鞍": "ān",
    "藉": "jí / jiè",
    "廊": "láng",
    "辇": "niǎn",
    "烂": "làn",
    "惹": "rě",
    "亚": "yà",
    "恪": "kè",
    "艰": "jiān",
    "竖": "shù",
    "咬": "yǎo",
    "榻": "tà",
    "箱": "xiāng",
    "滴": "dī",
    "衷": "zhōng",
    "辍": "chuò",
    "悠": "yōu",
    "邸": "dǐ",
    "瞒": "mán",
    "颉": "xié / jié",
    "誉": "yù",
    "踏": "tà",
    "怼": "duì",
    "俚": "lǐ",
    "俾": "bǐ",
    "僭": "jiàn",
    "讯": "xùn",
    "曜": "yào",
    "陨": "yǔn",
    "冕": "miǎn",
    "措": "cuò",
    "截": "jié",
    "麦": "nan",
    "销": "xiāo",
    "炀": "yáng",
    "龋": "qǔ",
    "欧": "ōu",
    "瘢": "bān",
    "叟": "sǒu",
    "凄": "qī",
    "焕": "huàn",
    "斛": "hú",
    "埂": "gěng",
    "狠": "hěn",
    "赍": "jī",
    "厨": "chú",
    "踪": "zōng",
    "播": "bō",
    "祗": "zhī",
    "缩": "suō",
    "霍": "huò",
    "坤": "kūn",
    "惮": "dàn",
    "挽": "wǎn",
    "恳": "kěn",
    "鞋": "xié",
    "确": "què",
    "炉": "lú",
    "沛": "pèi",
    "裙": "qún",
    "茅": "máo",
    "评": "píng",
    "猓": "guǒ",
    "批": "pī",
    "牒": "dié",
    "忿": "fèn",
    "锭": "dìng",
    "簦": "dēng",
    "顽": "wán",
    "拖": "tuō",
    "窜": "cuàn",
    "栽": "zāi",
    "纤": "qiàn / xiān",
    "坑": "kēng",
    "檄": "xí",
    "崖": "yái / yá",
    "骗": "piàn",
    "痕": "hén",
    "疼": "téng",
    "巷": "xiàng",
    "透": "tòu",
    "洒": "sǎ",
    "聊": "liáo",
    "迳": "jìng",
    "触": "chù",
    "褐": "hè",
    "矩": "jǔ",
    "暑": "shǔ",
    "攸": "yōu",
    "膳": "shàn",
    "氐": "dī / dǐ",
    "闾": "lú: / lv",
    "核": "hé",
    "婴": "yīng",
    "梳": "shū",
    "鼠": "shǔ",
    "硕": "shuò",
    "涛": "tāo",
    "啵": "bo",
    "铩": "shā",
    "欤": "yú",
    "绮": "qǐ",
    "沃": "wò",
    "碑": "bēi",
    "祷": "dǎo",
    "札": "zhá",
    "叮": "dīng",
    "促": "cù",
    "蠲": "juān",
    "硬": "yìng",
    "磕": "kē",
    "喻": "yù",
    "梨": "lí",
    "漫": "màn",
    "觯": "zhì",
    "睹": "dǔ",
    "胄": "zhòu",
    "裂": "liè",
    "矫": "jiǎo",
    "蛟": "jiāo",
    "玺": "xǐ",
    "砦": "zhài",
    "咨": "zī",
    "堕": "duò",
    "霄": "xiāo",
    "饿": "è",
    "孽": "niè",
    "闵": "mǐn",
    "鸯": "yāng",
    "禾": "hé",
    "挟": "jiā / xié",
    "鄂": "è / è",
    "裹": "guǒ",
    "骆": "luò",
    "旷": "kuàng",
    "渴": "kě",
    "捐": "juān",
    "斟": "zhēn",
    "滥": "làn",
    "虐": "nuè",
    "枚": "méi",
    "纬": "wěi",
    "辜": "gū",
    "檀": "tán",
    "掖": "yē / yè",
    "伲": "nì",
    "抛": "pāo",
    "帷": "wéi",
    "蝶": "dié",
    "球": "qíu",
    "态": "tài",
    "俘": "fú",
    "妥": "tuǒ",
    "沂": "yí",
    "冈": "gāng",
    "栋": "dòng",
    "弩": "nǔ",
    "煜": "yù",
    "鹏": "péng",
    "菊": "jú",
    "浊": "zhuó",
    "穑": "sè",
    "盏": "zhǎn",
    "倭": "wō",
    "粲": "càn",
    "翊": "yì",
    "懒": "lǎn",
    "畅": "chàng",
    "僖": "xī",
    "枯": "kū",
    "忆": "yì",
    "筹": "chóu",
    "汾": "fén",
    "胖": "pàng",
    "栖": "qī / xī",
    "拆": "chāi",
    "盆": "pén",
    "唇": "chún",
    "阮": "ruǎn",
    "握": "wò",
    "鬟": "huán",
    "叱": "chì",
    "鄴": "yè",
    "倦": "juàn",
    "湛": "zhàn",
    "骠": "piào / biāo",
    "袋": "dài",
    "棋": "qí",
    "雇": "gù",
    "祁": "qí",
    "甥": "shēng",
    "钧": "nan",
    "衮": "gǔn",
    "蚀": "shí",
    "宥": "yòu",
    "喇": "lā / lǎ",
    "谊": "yì",
    "耽": "dān",
    "叠": "dié",
    "掷": "zhì",
    "庾": "yǔ",
    "赌": "dǔ",
    "臾": "yú",
    "宸": "chén",
    "畔": "pàn",
    "笺": "jiān",
    "薪": "xīn",
    "艾": "ài",
    "纣": "zhòu",
    "娄": "lóu",
    "耄": "mào",
    "兔": "tù",
    "鹰": "yīng",
    "颁": "bān",
    "糊": "hú / hù",
    "偿": "cháng",
    "颐": "yí",
    "叉": "chā / chá / chǎ",
    "衅": "xìn",
    "饱": "bǎo",
    "绅": "shēn",
    "沾": "zhān",
    "仿": "fǎng",
    "罔": "wǎng",
    "摩": "mó",
    "溺": "nì / niào",
    "肇": "zhào",
    "戟": "jǐ",
    "魄": "pò",
    "谩": "mán / màn",
    "觅": "mì",
    "缗": "mín",
    "浣": "huàn",
    "票": "piào",
    "矜": "jīn",
    "盼": "pàn",
    "郢": "yǐng",
    "诙": "huī",
    "佞": "nìng",
    "拣": "jiǎn",
    "滞": "zhì",
    "悖": "bèi",
    "胥": "xū",
    "呜": "wū",
    "膝": "xī",
    "琳": "lín",
    "析": "xī",
    "毙": "bì",
    "沮": "jǔ",
    "姥": "lǎo / mǔ",
    "荀": "xún",
    "恣": "zì",
    "坡": "pō",
    "贷": "dài",
    "爬": "pá",
    "晟": "shèng",
    "泗": "sì",
    "漆": "qī",
    "谭": "tán",
    "谪": "zhé",
    "控": "kòng",
    "洹": "huán",
    "劣": "liè",
    "藩": "fān",
    "亨": "hēng",
    "乳": "rǔ",
    "肝": "gān",
    "幅": "fú",
    "技": "jì",
    "阑": "lán",
    "峡": "xiá",
    "耆": "qí",
    "嘻": "xī",
    "拐": "guǎi",
    "凿": "záo / zuò",
    "纂": "zuǎn",
    "鬓": "bìn",
    "圈": "juān / juàn / quān",
    "笙": "shēng",
    "笏": "hù",
    "琏": "liǎn",
    "傲": "ào",
    "撤": "chè",
    "耿": "gěng",
    "瘦": "shòu",
    "慨": "kǎi",
    "夸": "kuā",
    "睦": "mù",
    "钻": "zuān / zuàn",
    "皓": "hào",
    "拧": "níng / nǐng / nìng",
    "恁": "rèn / nín",
    "唷": "yō",
    "俨": "yǎn",
    "铭": "míng",
    "丸": "wán",
    "蚕": "cán",
    "迥": "jiǒng",
    "凇": "sōng",
    "徇": "xùn",
    "樵": "qiáo",
    "妒": "dù",
    "酋": "qíu",
    "琅": "láng",
    "洽": "qià",
    "秃": "tū",
    "邹": "zōu",
    "猷": "yóu",
    "蓟": "jì",
    "爰": "yuán",
    "奢": "shē",
    "潼": "tóng",
    "斌": "bīn",
    "巍": "wēi",
    "坦": "tǎn",
    "稹": "zhěn",
    "讥": "jī",
    "濮": "pú",
    "浓": "nóng",
    "跋": "bá",
    "耗": "hào",
    "浸": "jìn",
    "肴": "yáo",
    "摺": "zhé",
    "凰": "huáng",
    "俎": "zǔ",
    "俏": "qiào",
    "脉": "nan",
    "诲": "huì",
    "灼": "zhuó",
    "夔": "kuí",
    "栏": "lán",
    "罹": "lí",
    "渥": "wò",
    "鹊": "què",
    "狭": "xiá",
    "祯": "zhēn",
    "彝": "yí",
    "驳": "bó",
    "抓": "zhuā",
    "谗": "chán",
    "嫡": "dí",
    "簟": "diàn",
    "蓉": "róng",
    "抹": "mǒ / mò",
    "梓": "zǐ",
    "餐": "cān",
    "喧": "xuān",
    "胪": "lú",
    "迪": "dí",
    "粤": "yuè",
    "贩": "fàn",
    "冶": "yě",
    "蹈": "dǎo",
    "针": "zhēn",
    "匀": "yún",
    "孜": "zī",
    "冉": "rǎn",
    "窝": "wō",
    "稼": "jià",
    "溜": "līu",
    "汀": "tīng",
    "迈": "nan",
    "迩": "ěr",
    "胶": "jiāo",
    "纶": "lún",
    "饬": "chì",
    "谬": "mìu",
    "卸": "xiè",
    "瑟": "sè",
    "裘": "qíu",
    "惯": "guàn",
    "邕": "yōng",
    "嗽": "sòu",
    "孕": "yùn",
    "馔": "zhuàn",
    "逋": "bū",
    "琦": "qí",
    "赡": "shàn",
    "牡": "mǔ",
    "匣": "xiá",
    "缕": "lǔ: / lv",
    "珊": "shān",
    "羁": "jī",
    "笾": "biān",
    "贿": "huì",
    "奕": "yì",
    "箫": "xiāo",
    "迭": "dié",
    "眩": "xuàn",
    "羲": "xī",
    "昊": "hào",
    "摹": "mó",
    "桐": "tóng",
    "谘": "zī",
    "弁": "biàn",
    "贻": "yí",
    "悼": "dào",
    "剪": "jiǎn",
    "缮": "shàn",
    "榷": "què",
    "拙": "zhuó / zhuō",
    "濠": "háo",
    "挠": "náo",
    "髦": "máo",
    "椤": "luó",
    "酢": "zuò",
    "涯": "yá",
    "笥": "sì",
    "簇": "cù",
    "啤": "pí",
    "琛": "chēn",
    "孺": "rú",
    "渎": "dú",
    "廪": "lǐn",
    "坝": "bà",
    "雯": "wén",
    "酷": "kù",
    "挨": "āi / ái",
    "瑜": "yú",
    "惩": "chéng",
    "缝": "féng / fèng",
    "湿": "shī",
    "剖": "pōu",
    "僮": "tóng / zhuàng",
    "笛": "dí",
    "柯": "kē",
    "芍": "sháo",
    "涌": "yǒng",
    "迨": "dài",
    "遐": "xiá",
    "讽": "fèng / fěng",
    "酣": "hān",
    "俞": "yú",
    "扈": "hù",
    "奎": "kuí",
    "魅": "mèi",
    "辔": "pèi",
    "沐": "mù",
    "瑾": "jǐn",
    "帕": "pà",
    "译": "yì",
    "旭": "xù",
    "罩": "zhào",
    "劲": "jìn / jìng",
    "滔": "tāo",
    "颈": "jǐng",
    "舱": "cāng",
    "腊": "là",
    "桧": "guì",
    "袄": "ǎo",
    "翘": "qiáo / qiào",
    "嬷": "mā / mó",
    "驸": "fù",
    "纨": "wán",
    "岱": "dài",
    "腥": "xīng",
    "痪": "huàn",
    "障": "zhàng",
    "幔": "màn",
    "劈": "pī / pǐ",
    "缎": "duàn",
    "梧": "wú",
    "萌": "méng",
    "眠": "mián",
    "韬": "tāo",
    "鞫": "jū",
    "骤": "zhòu",
    "壑": "hè",
    "钏": "chuàn",
    "础": "chǔ",
    "藻": "zǎo",
    "喽": "lóu / lou",
    "谌": "chén",
    "尖": "jiān",
    "亿": "yì",
    "铨": "quán",
    "贲": "bēn / bì",
    "圭": "guī",
    "泼": "pō",
    "膺": "yīng",
    "卤": "lǔ",
    "偈": "jì / jié",
    "狻": "suān",
    "砸": "zá",
    "斡": "wò",
    "跨": "kuà",
    "栅": "zhà / shān",
    "钰": "yù",
    "筠": "yún",
    "辂": "lù",
    "煞": "shā / shà",
    "碰": "pèng",
    "谱": "pǔ",
    "挤": "jǐ",
    "虢": "guó",
    "掾": "yuàn",
    "睁": "zhēng",
    "晔": "yè",
    "蕙": "huì",
    "闯": "chuǎng",
    "恸": "tòng",
    "碍": "ài",
    "阜": "fù",
    "簪": "zān",
    "徊": "huái",
    "漳": "zhāng",
    "咒": "zhòu",
    "绫": "líng",
    "掘": "jué",
    "傥": "tǎng",
    "嫔": "pín",
    "蟠": "pán",
    "搅": "jiǎo",
    "觽": "wéi",
    "缪": "miào / móu",
    "湟": "huáng",
    "裨": "bì / pí",
    "棠": "táng",
    "谤": "bàng",
    "陟": "zhì",
    "剥": "bō / bāo",
    "钺": "yuè",
    "妫": "guī",
    "裔": "yì",
    "骏": "nan",
    "隅": "yú",
    "函": "hán",
    "逞": "chěng",
    "盒": "hé",
    "湾": "wān",
    "雹": "báo",
    "牟": "móu",
    "涧": "jiàn",
    "皂": "zào",
    "闽": "mǐn",
    "钤": "qián",
    "竺": "zhú",
    "渚": "zhǔ",
    "蕉": "jiāo",
    "蠕": "rú",
    "涫": "guàn",
    "夙": "sù",
    "谄": "chǎn",
    "桩": "zhuāng",
    "幌": "huǎng",
    "僻": "pì",
    "瞎": "xiā",
    "刮": "guā",
    "甄": "zhēn",
    "滨": "bīn",
    "蠓": "měng",
    "帧": "zhèng / zhēn",
    "蕴": "yùn",
    "菹": "zū",
    "笞": "chī",
    "夭": "yāo",
    "忤": "wǔ",
    "稚": "zhì",
    "鹘": "hú / gǔ",
    "渲": "xuàn",
    "彬": "bīn",
    "衾": "qīn",
    "纥": "gē / hé",
    "檐": "yán",
    "婉": "wǎn",
    "蓄": "xù",
    "梯": "tī",
    "倩": "qiàn",
    "忻": "xīn",
    "版": "bǎn",
    "丕": "pī",
    "钜": "jù",
    "鸦": "yā",
    "爪": "zhuǎ / zhǎo",
    "熬": "āo / áo",
    "肖": "xiào / xiāo",
    "谔": "è",
    "冻": "dòng",
    "鞅": "yǎng / yāng",
    "歹": "dǎi",
    "佟": "tóng",
    "瑰": "guī",
    "扣": "kòu",
    "毓": "yù",
    "诡": "guǐ",
    "脂": "zhī",
    "厂": "chǎng",
    "虹": "hóng / jiàng",
    "胫": "jìng",
    "涨": "zhǎng / zhàng",
    "牍": "dú",
    "靴": "xuē",
    "娟": "juān",
    "竿": "gān",
    "銮": "luán",
    "柜": "guì / jǔ",
    "谴": "qiǎn",
    "锤": "chuí",
    "簧": "huáng",
    "寐": "mèi",
    "纹": "wén",
    "絮": "xù",
    "缀": "zhuì",
    "稿": "gǎo",
    "郏": "jiá",
    "弑": "shì",
    "缉": "qī / jī",
    "钉": "dīng / dìng",
    "滩": "tān",
    "蹋": "tà",
    "枣": "zǎo",
    "亢": "kàng",
    "酸": "suān",
    "赉": "lài",
    "捣": "dǎo",
    "栗": "lì",
    "赢": "yíng",
    "厘": "lí",
    "芙": "fú",
    "郧": "yún",
    "孛": "bèi / bó",
    "挛": "luán",
    "缴": "jiǎo",
    "昶": "chǎng",
    "侈": "chǐ",
    "臭": "chòu / xìu",
    "笠": "lì",
    "觥": "gōng",
    "绾": "wǎn",
    "醴": "lǐ",
    "遏": "è",
    "钢": "gāng",
    "骚": "sāo",
    "删": "shān",
    "蠼": "qú",
    "驼": "tuó",
    "剧": "jù",
    "摧": "cuī",
    "炭": "tàn",
    "猴": "hóu",
    "陌": "mò",
    "蟆": "má / ma",
    "椿": "chūn / chún",
    "抟": "tuán",
    "灿": "càn",
    "荫": "yìn / yīn",
    "狡": "jiǎo",
    "醋": "cù",
    "愕": "è",
    "髯": "rán",
    "擦": "cā",
    "杲": "gǎo",
    "挡": "dǎng / dàng",
    "蛔": "huí",
    "衢": "qú",
    "渤": "bó",
    "柩": "jìu",
    "滕": "téng",
    "旺": "wàng",
    "禧": "xǐ",
    "诀": "jué",
    "诮": "qiào",
    "谖": "xuān",
    "爸": "bà",
    "漠": "mò",
    "擞": "sǒu",
    "焰": "yàn",
    "侮": "wǔ",
    "碌": "lù",
    "蔚": "wèi / yù",
    "吒": "zhà",
    "佣": "yōng / yòng",
    "侨": "qiáo",
    "兜": "dōu",
    "氖": "nǎi",
    "蜂": "fēng",
    "嗜": "shì",
    "涿": "zhuō",
    "淄": "zī",
    "卞": "biàn",
    "膏": "gāo",
    "叨": "dāo / tāo",
    "秽": "huì",
    "绞": "jiǎo",
    "裤": "kù",
    "郓": "yùn",
    "陋": "lòu",
    "喀": "kā",
    "谯": "qiáo / qiào",
    "孚": "fú",
    "豕": "shǐ",
    "攘": "rǎng",
    "屑": "xiè",
    "胎": "tāi",
    "谀": "yú",
    "驹": "jū",
    "嗳": "ǎi / ài",
    "谎": "huǎng",
    "抡": "lūn / lún",
    "叭": "bā",
    "譬": "pì",
    "谧": "mì",
    "匾": "biǎn / pián",
    "奥": "ào",
    "苤": "piě",
    "瘛": "chì",
    "绸": "chóu",
    "觞": "shāng",
    "殡": "bìn",
    "兑": "duì",
    "毡": "zhān",
    "励": "lì",
    "森": "sēn",
    "刍": "chú",
    "曷": "hé",
    "雌": "cí",
    "筋": "jīn",
    "弯": "wān",
    "缢": "yì",
    "钡": "bèi",
    "躯": "qū",
    "桀": "jié",
    "蛉": "líng",
    "菱": "líng",
    "撇": "piē / piě",
    "妪": "yù",
    "跸": "bì",
    "郝": "hǎo",
    "邠": "bīn",
    "溆": "xù",
    "劭": "shào",
    "港": "gǎng",
    "秸": "jiē",
    "讶": "yà",
    "叁": "sān",
    "侃": "kǎn",
    "奄": "yān / yǎn",
    "苛": "kē",
    "熘": "līu",
    "蟾": "chán",
    "芒": "máng",
    "扒": "bā / pá",
    "诔": "lěi",
    "榆": "yú",
    "煮": "zhǔ",
    "祔": "fù",
    "琶": "pá",
    "媪": "ǎo",
    "缙": "jìn",
    "杞": "qǐ",
    "懂": "dǒng",
    "峭": "qiào",
    "掀": "xiān",
    "钥": "yào / yuè",
    "砲": "pào",
    "葜": "qiā",
    "蹙": "cù",
    "甸": "diàn",
    "箕": "jī",
    "涓": "juān",
    "脊": "jǐ",
    "馨": "xīn",
    "湮": "yān / yīn",
    "枭": "xiāo",
    "漂": "piāo / piǎo / piào",
    "薰": "xūn",
    "楷": "kǎi",
    "刁": "diāo",
    "襟": "jīn",
    "樽": "zūn",
    "壤": "rǎng",
    "疫": "yì",
    "浇": "jiāo",
    "繇": "yáo / yóu / zhòu",
    "搁": "gē",
    "籴": "dí",
    "株": "zhū",
    "笆": "bā",
    "椒": "jiāo",
    "抖": "dǒu",
    "肿": "zhǒng",
    "雉": "zhì",
    "鬻": "yù",
    "您": "nín",
    "谣": "yáo",
    "隘": "ài",
    "凯": "kǎi",
    "涣": "huàn",
    "喉": "hóu",
    "犀": "xī",
    "炳": "bǐng",
    "钓": "diào",
    "咧": "liē / liě",
    "镂": "lòu",
    "刊": "kān",
    "曳": "yè",
    "掣": "chè",
    "颗": "kē",
    "坎": "kǎn",
    "廖": "liào",
    "侣": "lǔ: / lv",
    "邺": "yè",
    "鞠": "jū",
    "谙": "ān",
    "袅": "niǎo",
    "虾": "xiā",
    "愍": "mǐn",
    "捆": "kǔn",
    "蠹": "dù",
    "讹": "é",
    "络": "lào / luò",
    "摘": "zhāi",
    "敞": "chǎng",
    "杆": "gān / gǎn",
    "诠": "quán",
    "侥": "jiǎo / yáo",
    "诤": "zhèng",
    "昙": "tán",
    "曼": "màn",
    "谠": "dǎng",
    "栾": "luán",
    "诫": "jiè",
    "炕": "kàng",
    "讷": "nè",
    "饼": "bǐng",
    "橐": "tuó",
    "兖": "yǎn",
    "幡": "fān",
    "涞": "lái",
    "需": "xū",
    "诩": "xǔ",
    "觐": "jìn",
    "悍": "hàn",
    "蜡": "là",
    "圃": "pǔ",
    "醇": "chún",
    "鳞": "lín",
    "瀛": "yíng",
    "霖": "lín",
    "妗": "jìn",
    "棘": "jí",
    "磐": "pán",
    "铡": "zhá",
    "篆": "zhuàn",
    "殁": "mò",
    "绑": "bǎng",
    "绯": "fēi",
    "裰": "duō",
    "蕊": "ruǐ",
    "溥": "pǔ",
    "订": "dìng",
    "懈": "xiè",
    "砂": "shā",
    "饕": "tāo",
    "峤": "jiào / qiáo",
    "帆": "fān",
    "蕖": "qú",
    "怂": "sǒng",
    "琮": "cóng",
    "笫": "zǐ",
    "镏": "líu",
    "沁": "qìn",
    "贮": "zhù",
    "乍": "zhà",
    "捍": "hàn",
    "兢": "jīng",
    "倌": "guān",
    "畴": "chóu",
    "懦": "nuò",
    "鞘": "qiào",
    "趾": "zhǐ",
    "澳": "ào",
    "拗": "ào / nìu",
    "倡": "chàng",
    "阖": "gé / hé",
    "钊": "zhāo",
    "酝": "yùn",
    "嫉": "jí",
    "朽": "xǐu",
    "挣": "zhēng / zhèng",
    "堋": "péng",
    "糜": "mí",
    "怅": "chàng",
    "儆": "jǐng",
    "膊": "bó",
    "铃": "líng",
    "堑": "qiàn",
    "槛": "jiàn / kǎn",
    "廓": "kuò",
    "琨": "kūn",
    "耙": "bà / pá",
    "褂": "guà",
    "谝": "piǎn",
    "喷": "pēn / pèn",
    "估": "gū / gù",
    "嗔": "chēn",
    "购": "gòu",
    "锺": "zhōng",
    "嫣": "yān",
    "歆": "xīn",
    "瞬": "shùn",
    "躺": "tǎng",
    "赔": "péi",
    "芸": "yún",
    "伎": "jì",
    "沽": "gū",
    "懋": "mào",
    "潦": "lǎo / liáo",
    "颓": "tuí",
    "濉": "suī",
    "暨": "jì",
    "诖": "guà",
    "邈": "miǎo",
    "慷": "kāng",
    "彗": "huì",
    "罄": "qìng",
    "缸": "gāng",
    "吁": "xū / yù",
    "胧": "lóng",
    "噶": "gá",
    "愆": "qiān",
    "哨": "shào",
    "噪": "zào",
    "陂": "pí / pō / bēi",
    "瑁": "mào",
    "髻": "jì",
    "沸": "fèi",
    "绘": "huì",
    "猩": "xīng",
    "躁": "zào",
    "殖": "zhí",
    "憾": "hàn",
    "揆": "kuí",
    "篡": "cuàn",
    "腔": "qiāng",
    "藤": "téng",
    "刹": "chà / shā",
    "髂": "qià",
    "涤": "dí",
    "枷": "jiā",
    "纭": "yún",
    "徘": "pái",
    "惫": "bèi",
    "蚁": "yǐ",
    "懊": "ào",
    "糁": "sǎn / shēn",
    "扭": "nǐu",
    "灶": "zào",
    "债": "zhài",
    "匝": "zā",
    "稻": "dào",
    "芜": "wú",
    "肤": "fū",
    "夤": "yín",
    "肺": "fèi",
    "咭": "jī",
    "腐": "fǔ",
    "迤": "yí / yǐ",
    "闱": "wéi",
    "黔": "qián",
    "跻": "jī",
    "翅": "chì",
    "斫": "zhuó",
    "翩": "piān",
    "戾": "lì",
    "嘀": "dí / dī",
    "拈": "niān",
    "渌": "lù",
    "舰": "jiàn",
    "磺": "huáng",
    "疮": "chuāng",
    "鹅": "é",
    "橹": "lǔ",
    "峦": "luán",
    "饲": "sì",
    "伶": "líng",
    "嵌": "qiàn",
    "综": "zōng",
    "怡": "yí",
    "岫": "xìu",
    "炽": "chì",
    "咳": "hāi / ké",
    "桶": "tǒng",
    "蒸": "zhēng",
    "毂": "gū / gǔ",
    "僦": "jìu",
    "捏": "niē",
    "匏": "páo",
    "赀": "zī",
    "觑": "qù",
    "圜": "huán / yuán",
    "畋": "tián",
    "黍": "shǔ",
    "烁": "shuò",
    "偎": "wēi",
    "赜": "zé",
    "粥": "zhōu",
    "轸": "zhěn",
    "皎": "jiǎo",
    "贸": "mào",
    "粘": "nián / zhān",
    "骋": "chěng",
    "卵": "luǎn",
    "磬": "qìng",
    "熹": "xī",
    "熳": "màn",
    "沔": "miǎn",
    "燃": "rán",
    "鹃": "juān",
    "椭": "tuǒ",
    "谡": "sù",
    "阕": "què",
    "搂": "lōu / lǒu",
    "堵": "dǔ",
    "鹄": "gǔ / hú",
    "淘": "táo",
    "闸": "zhá",
    "钪": "kàng",
    "槊": "shuò",
    "扼": "è",
    "殴": "ōu",
    "哟": "yo / yō",
    "撼": "hàn",
    "詈": "lì",
    "褥": "rù",
    "研": "yán",
    "蜕": "tuì",
    "巩": "gǒng",
    "蹇": "jiǎn",
    "踊": "yǒng",
    "蹦": "bèng",
    "浔": "xún",
    "搿": "gé",
    "绷": "bēng / běng",
    "啸": "xiào",
    "堰": "yàn",
    "獭": "tǎ",
    "槭": "qì",
    "狈": "bèi",
    "璞": "pú",
    "麓": "lù",
    "鸭": "yā",
    "液": "yè",
    "猗": "yī",
    "墒": "shāng",
    "琪": "qí",
    "筒": "tǒng",
    "葵": "kuí",
    "玳": "dài",
    "蛭": "zhì",
    "舫": "fǎng",
    "沦": "lún",
    "谮": "zèn",
    "幢": "chuáng / zhuàng",
    "咦": "yí",
    "龚": "gōng",
    "豁": "huá / huō / huò",
    "缨": "yīng",
    "攒": "cuán / zǎn",
    "嫖": "piáo",
    "汇": "huì",
    "萦": "yíng",
    "晒": "shài",
    "菏": "hé",
    "勖": "xù",
    "昴": "mǎo",
    "栈": "zhàn",
    "芄": "wán",
    "骧": "xiāng",
    "煎": "jiān",
    "荥": "xíng / yíng",
    "雒": "luò",
    "辆": "liàng",
    "娱": "yú",
    "窟": "kū",
    "泻": "xiè",
    "葱": "cōng",
    "匮": "kuì",
    "辑": "jí",
    "拷": "kǎo",
    "拯": "zhěng",
    "悴": "cuì",
    "屁": "pì",
    "莹": "yíng",
    "燮": "xiè",
    "邱": "qīu",
    "壅": "yōng",
    "蝉": "chán",
    "弛": "chí",
    "吸": "xī",
    "萍": "píng",
    "翌": "yì",
    "驭": "yù",
    "轴": "zhóu / zhú",
    "袂": "mèi",
    "韂": "chàn",
    "拽": "yè / zhuāi / zhuài",
    "苌": "cháng",
    "航": "háng",
    "扔": "rēng",
    "嗤": "chī",
    "洮": "táo",
    "捶": "chuí",
    "掇": "duō",
    "券": "quàn",
    "蟹": "xiè",
    "亳": "bó",
    "瞿": "jù / qú",
    "蠡": "lí / lǐ",
    "緝": "jī",
    "竦": "sǒng",
    "厄": "è",
    "挖": "wā",
    "翦": "jiǎn",
    "莅": "lì",
    "揽": "lǎn",
    "砚": "yàn",
    "鄜": "fū",
    "仑": "lún",
    "藕": "ǒu",
    "嘶": "sī",
    "庖": "páo",
    "喘": "chuǎn",
    "溉": "gài",
    "寤": "wù",
    "杳": "yǎo",
    "踔": "chuō",
    "嬉": "xī",
    "蚴": "yòu",
    "浆": "jiāng / jiàng",
    "贽": "zhì",
    "赚": "zhuàn / zuàn",
    "跷": "qiāo",
    "癫": "diān",
    "饯": "jiàn",
    "旒": "líu",
    "跏": "jiā",
    "庠": "xiáng",
    "鄱": "pó",
    "颢": "hào",
    "驮": "duò / tuó",
    "歪": "wāi",
    "狸": "lí",
    "咕": "gū",
    "韭": "jǐu",
    "逡": "qūn",
    "涔": "cén",
    "臁": "lián",
    "垦": "kěn",
    "逝": "shì",
    "寰": "huán",
    "晷": "guǐ",
    "雠": "chóu",
    "彤": "tóng",
    "洳": "rù",
    "吵": "chǎo",
    "踵": "zhǒng",
    "奂": "huàn",
    "醮": "jiào",
    "痹": "bì",
    "氤": "yīn",
    "谛": "dì",
    "挚": "zhì",
    "倏": "shū",
    "炙": "zhì",
    "蓿": "xu",
    "疗": "liáo",
    "壹": "yī",
    "獠": "liáo",
    "琵": "pí",
    "恺": "kǎi",
    "砖": "zhuān",
    "盥": "guàn",
    "嗄": "á / shà",
    "歉": "qiàn",
    "邯": "hán",
    "鸨": "bǎo",
    "呤": "líng / lìng",
    "衬": "chèn",
    "忝": "tiǎn",
    "诧": "chà",
    "澜": "lán",
    "涎": "xián",
    "肮": "āng",
    "蠢": "chǔn",
    "颊": "jiá",
    "乓": "pāng",
    "婺": "wù",
    "貂": "diāo",
    "蹄": "tí",
    "篱": "lí",
    "逍": "xiāo",
    "戬": "jiǎn",
    "阼": "zuò",
    "冗": "rǒng",
    "挫": "cuò",
    "羹": "gēng",
    "俦": "chóu",
    "犊": "dú",
    "粢": "zī",
    "赣": "gàn",
    "拭": "shì",
    "茉": "mò",
    "盎": "àng",
    "搀": "chān",
    "滦": "luán",
    "拼": "pīn",
    "赘": "zhuì",
    "狎": "xiá",
    "燧": "suì",
    "沓": "tà",
    "啦": "lā / la",
    "恬": "tián",
    "焙": "bèi",
    "缅": "miǎn",
    "凳": "dèng",
    "拚": "pàn / pīn",
    "帜": "zhì",
    "撩": "liāo / liáo",
    "渺": "miǎo",
    "嚣": "xiāo",
    "丐": "gài",
    "淙": "cóng",
    "煨": "wēi",
    "琢": "zhuó",
    "掳": "lǔ",
    "娜": "nuó / nà",
    "侔": "móu",
    "暹": "xiān",
    "骈": "pián",
    "捎": "shāo",
    "嚼": "jiáo / jué",
    "镒": "yì",
    "玫": "méi",
    "昕": "xīn",
    "傻": "shǎ",
    "嗖": "sōu",
    "袜": "wà",
    "矶": "jī",
    "挝": "zhuā / wō",
    "迅": "xùn",
    "棣": "dì",
    "帑": "tǎng",
    "蹲": "dūn",
    "苻": "fú",
    "凹": "āo",
    "骞": "qiān",
    "揣": "chuāi / chuǎi",
    "恙": "yàng",
    "琐": "suǒ",
    "湫": "jiǎo / qīu",
    "琰": "yǎn",
    "吨": "dūn / dùn",
    "酱": "jiàng",
    "矛": "máo",
    "嬖": "bì",
    "邳": "pī",
    "狩": "shòu",
    "逶": "wēi",
    "恂": "xún",
    "锅": "guō",
    "诟": "gòu",
    "幄": "wò",
    "娼": "chāng",
    "吝": "lìn",
    "褪": "tùn / tuì",
    "躔": "chán",
    "殉": "xùn",
    "莒": "jǔ",
    "蕲": "qí",
    "庑": "wǔ",
    "浼": "měi",
    "葫": "hú",
    "鹞": "yào",
    "嘤": "yīng",
    "聿": "yù",
    "铣": "xiǎn / xǐ",
    "怖": "bù",
    "檬": "méng",
    "嫩": "nèn",
    "蟪": "huì",
    "啖": "dàn",
    "烹": "pēng",
    "驯": "xún / xùn",
    "爻": "yáo",
    "凛": "lǐn",
    "芷": "zhǐ",
    "嘁": "qī",
    "逖": "tì",
    "诳": "kuáng",
    "厩": "jìu",
    "哑": "yā / yǎ",
    "诋": "dǐ",
    "拊": "fǔ",
    "昱": "yù",
    "蛞": "kuò",
    "殓": "liàn",
    "麒": "qí",
    "垢": "gòu",
    "呐": "nà / ne / na",
    "炊": "chuī",
    "荚": "jiá",
    "哺": "bū / bǔ",
    "魇": "yǎn",
    "厝": "cuò",
    "荼": "tú",
    "湃": "pài",
    "骥": "jì",
    "峨": "é",
    "泌": "bì / mì",
    "寞": "mò",
    "沼": "zhǎo",
    "傩": "nuó",
    "阐": "chǎn",
    "挈": "qiè",
    "覃": "tán",
    "扁": "biǎn / piān",
    "饺": "jiǎo",
    "纫": "rèn",
    "阉": "yān",
    "苞": "bāo",
    "闼": "tà",
    "努": "nǔ",
    "匚": "fāng / qū",
    "咄": "duō",
    "璃": "lí",
    "旄": "máo / mào",
    "饔": "yōng",
    "姆": "mǔ",
    "羰": "tāng",
    "犒": "kào",
    "缥": "piǎo / piāo",
    "曛": "xūn",
    "臼": "jìu",
    "寥": "liáo",
    "诜": "shēn",
    "臻": "zhēn",
    "钔": "mén",
    "茎": "jīng",
    "肱": "gōng",
    "畹": "wǎn",
    "脖": "bó",
    "胛": "jiǎ",
    "撑": "chēng",
    "绎": "yì",
    "朐": "qú",
    "潇": "xiāo",
    "踢": "tī",
    "痒": "yǎng",
    "琉": "líu",
    "吮": "shǔn",
    "醯": "xī",
    "麝": "shè",
    "缯": "zēng / zèng",
    "苯": "běn",
    "撕": "sī",
    "汛": "xùn",
    "萃": "cuì",
    "喙": "huì",
    "藜": "lí",
    "壳": "ké / qiào",
    "烙": "lào",
    "苇": "wěi",
    "迦": "jiā",
    "忒": "tè / tuī",
    "髃": "yú",
    "蛊": "gǔ",
    "瘴": "zhàng",
    "霎": "shà",
    "狮": "shī",
    "怏": "yàng",
    "锣": "luó",
    "晡": "bū",
    "蔬": "shū",
    "缶": "fǒu",
    "袢": "pàn",
    "踉": "liáng / liàng",
    "剽": "piāo",
    "憎": "zēng",
    "牖": "yǒu",
    "篮": "lán",
    "轼": "shì",
    "阆": "láng",
    "娑": "suō",
    "撬": "qiào",
    "鹦": "yīng",
    "俩": "liǎ / liǎng",
    "毗": "pí",
    "址": "zhǐ",
    "倨": "jù",
    "骡": "luó",
    "瞪": "dèng",
    "禘": "dì",
    "拴": "shuān",
    "鲋": "fù",
    "挞": "tà",
    "魑": "chī",
    "袱": "fú",
    "棚": "péng",
    "橛": "jué",
    "碇": "dìng",
    "窘": "jiǒng",
    "殃": "yāng",
    "俅": "qíu",
    "玛": "mǎ",
    "蛴": "qí",
    "揪": "jīu",
    "燎": "liáo",
    "屎": "shǐ",
    "蠖": "huò",
    "窄": "zhǎi",
    "穹": "qióng",
    "疯": "fēng",
    "划": "huá / huà",
    "蓖": "bì",
    "嗝": "gé",
    "翱": "áo",
    "鲤": "lǐ",
    "镌": "juān",
    "焓": "hán",
    "碛": "qì",
    "疽": "jū",
    "裎": "chéng",
    "氯": "lù: / lv",
    "筮": "shì",
    "鹑": "chún",
    "绽": "zhàn",
    "骊": "lí",
    "尬": "gà",
    "蛑": "móu",
    "迸": "bèng",
    "猫": "māo",
    "钵": "bō",
    "啬": "sè",
    "徼": "jiǎo / jiào",
    "隽": "nan",
    "迄": "qì",
    "勺": "sháo",
    "奁": "lián",
    "锢": "gù",
    "缰": "jiāng",
    "斑": "bān",
    "扛": "gāng / káng",
    "辎": "zī",
    "煲": "bāo",
    "峒": "tóng / dòng",
    "搏": "bó",
    "戳": "chuō",
    "拓": "tà / tuò",
    "舛": "chuǎn",
    "斐": "fěi",
    "棵": "kē",
    "瓮": "wèng",
    "串": "chuàn",
    "逗": "dòu",
    "喂": "wèi",
    "芮": "ruì",
    "绱": "shàng",
    "隍": "huáng",
    "萼": "è",
    "嗍": "suō",
    "焘": "dào / tāo",
    "镐": "gǎo / hào",
    "婶": "shěn",
    "俣": "yǔ",
    "旃": "zhān",
    "颙": "yú",
    "鹗": "è",
    "淋": "lìn / lín",
    "钍": "tǔ",
    "鬃": "zōng",
    "氲": "yūn",
    "芯": "xīn",
    "媛": "yuán / yuàn",
    "噬": "shì",
    "铀": "yóu",
    "辙": "chè / zhé",
    "昵": "nì",
    "舨": "bǎn",
    "呕": "ǒu",
    "涸": "hé",
    "捻": "niǎn",
    "卮": "zhī",
    "嶂": "zhàng",
    "擂": "léi / lèi",
    "笪": "dá",
    "绦": "tāo",
    "唾": "tuò",
    "惚": "hū",
    "虬": "qíu",
    "俪": "lì",
    "罴": "pí",
    "墩": "dūn",
    "馥": "fù",
    "跣": "xiǎn",
    "袒": "tǎn",
    "逯": "lù",
    "笳": "jiā",
    "粜": "tiào",
    "咴": "huī",
    "酪": "lào",
    "衿": "jīn",
    "靶": "bǎ",
    "痢": "lì",
    "邃": "suì",
    "蹑": "niè",
    "诒": "yí",
    "弈": "yì",
    "鸠": "jīu",
    "滓": "zǐ",
    "蔼": "ǎi",
    "殄": "tiǎn",
    "诓": "kuāng",
    "楫": "jí",
    "氛": "fēn",
    "阋": "xì",
    "恻": "cè",
    "壕": "háo",
    "悯": "mǐn",
    "柬": "jiǎn",
    "哼": "hēng / hng",
    "胃": "wèi",
    "倬": "zhuō",
    "瘗": "yì",
    "茨": "cí",
    "饵": "ěr",
    "瓒": "zàn",
    "剂": "jì",
    "砺": "lì",
    "盍": "hé",
    "钿": "diàn / tián",
    "菟": "tù / tú",
    "锵": "qiāng",
    "窈": "yǎo",
    "蟒": "mǎng",
    "椎": "chuí / zhuī",
    "塾": "shú",
    "踌": "chóu",
    "牝": "pìn",
    "蚨": "fú",
    "涟": "lián",
    "呷": "xiā / gā",
    "谇": "suì",
    "罟": "gǔ",
    "猾": "huá",
    "徭": "yáo",
    "铠": "kǎi",
    "曩": "nǎng",
    "嗉": "sù",
    "馑": "jǐn",
    "瑚": "hú",
    "扳": "bān / pān",
    "霁": "jì",
    "洎": "jì",
    "蛩": "qióng",
    "澶": "chán",
    "彀": "gòu",
    "鸪": "gū",
    "佯": "yáng",
    "髡": "kūn",
    "荻": "dí",
    "闳": "hóng",
    "挪": "nuó",
    "棱": "léng",
    "汹": "xiōng",
    "毖": "bì",
    "逻": "luó",
    "趟": "tàng",
    "菲": "fēi",
    "迂": "yū",
    "窖": "jiào",
    "菽": "shū",
    "淤": "yū",
    "醢": "hǎi",
    "诿": "wěi",
    "饴": "yí",
    "莘": "shēn / xīn",
    "笄": "jī",
    "婕": "jié",
    "胺": "àn",
    "灏": "hào",
    "墀": "chí",
    "涑": "sù",
    "鹬": "yù",
    "筛": "shāi",
    "账": "zhàng",
    "锏": "jiǎn",
    "逦": "lǐ",
    "匙": "chí / shi",
    "盔": "kuī",
    "琬": "wǎn",
    "盾": "dùn",
    "掏": "tāo",
    "厦": "shà / xià",
    "嶷": "yí",
    "黯": "àn",
    "岷": "mín",
    "憔": "qiáo",
    "煊": "xuān",
    "锍": "lǐu",
    "裼": "tì",
    "漱": "shù",
    "颛": "zhuān",
    "蜜": "mì",
    "哦": "é / ó / ò",
    "芤": "kōu",
    "阂": "hé",
    "忖": "cǔn",
    "魃": "bá",
    "楹": "yíng",
    "杵": "chǔ",
    "型": "xíng",
    "腚": "dìng",
    "勰": "xié",
    "秤": "chěng / chèng",
    "茗": "míng",
    "吆": "yāo",
    "煳": "hú",
    "桢": "zhēn",
    "棹": "zhuō / zhào",
    "郴": "chēn",
    "躇": "chú",
    "吼": "hǒu",
    "帻": "zé",
    "顗": "yǐ",
    "凋": "diāo",
    "惰": "duò",
    "跛": "bǒ",
    "胙": "zuò",
    "蛾": "é",
    "粪": "fèn",
    "顼": "xù / xū",
    "镆": "mò",
    "舶": "bó",
    "佃": "diàn",
    "捱": "ái",
    "髀": "bì",
    "阏": "è / yān",
    "汶": "wèn",
    "閤": "gē",
    "锥": "zhuī",
    "淅": "xī",
    "鞯": "jiān",
    "阃": "kǔn",
    "祫": "xiá",
    "莆": "pú",
    "裾": "jū",
    "亘": "gèn",
    "诹": "zōu",
    "啻": "chì",
    "渖": "shěn",
    "祇": "qí",
    "犁": "lí",
    "悌": "tì",
    "拇": "mǔ",
    "鋈": "wù",
    "暝": "míng",
    "哗": "huā / huá",
    "谜": "mí",
    "糟": "zāo",
    "鍪": "móu",
    "嘲": "cháo / zhāo",
    "售": "shòu",
    "邾": "zhū",
    "坪": "píng",
    "渫": "xiè",
    "炜": "wěi",
    "蛋": "dàn",
    "蛹": "yǒng",
    "炅": "guì",
    "撮": "cuō",
    "吠": "fèi",
    "霆": "tíng",
    "疤": "bā",
    "嘈": "cáo",
    "绻": "quǎn",
    "斓": "lán",
    "涵": "hán",
    "脾": "pí",
    "宕": "dàng",
    "艄": "shāo",
    "偌": "ruò",
    "瑕": "xiá",
    "踩": "cǎi",
    "墟": "xū",
    "鸱": "chī",
    "茹": "rú",
    "菔": "fú",
    "鸥": "ōu",
    "燔": "fán",
    "篷": "péng",
    "皱": "zhòu",
    "阄": "jīu",
    "麽": "mó / me",
    "祜": "hù",
    "磁": "cí",
    "锜": "yǐ",
    "笮": "zé",
    "淖": "nào",
    "卣": "yǒu",
    "暄": "xuān",
    "歙": "shè / xī",
    "醪": "láo",
    "熏": "xūn",
    "祉": "zhǐ",
    "袷": "jiá",
    "捞": "lāo",
    "羯": "jié",
    "缫": "sāo",
    "埔": "pǔ",
    "症": "zhēng / zhèng",
    "酵": "jiào",
    "腕": "wàn",
    "淦": "gàn",
    "瓯": "ōu",
    "茸": "róng",
    "蜃": "shèn",
    "粑": "bā",
    "奘": "zàng / zhuǎng",
    "擎": "qíng",
    "芪": "qí",
    "臀": "tún",
    "渝": "yú",
    "拮": "jié",
    "鹭": "lù",
    "跤": "jiāo",
    "阒": "qù",
    "羸": "léi",
    "笸": "pǒ",
    "鑫": "xīn",
    "轰": "hōng",
    "颎": "jiǒng",
    "氨": "ān",
    "岚": "lán",
    "瘟": "wēn",
    "邛": "qióng",
    "苁": "cōng",
    "娉": "pīng",
    "穰": "ráng",
    "叵": "pǒ",
    "珙": "gǒng",
    "澈": "chè",
    "培": "péi",
    "腮": "sāi",
    "薮": "sǒu",
    "煤": "méi",
    "癞": "lài",
    "珥": "ěr",
    "颔": "hàn",
    "胰": "yí",
    "宄": "guǐ",
    "珂": "kē",
    "餍": "yàn",
    "穀": "yù",
    "哚": "duǒ",
    "愉": "yú",
    "鄢": "yān",
    "箸": "zhù",
    "荔": "lì",
    "扉": "fēi",
    "鳖": "biē",
    "诽": "fěi",
    "伽": "qié / gā",
    "份": "fèn",
    "釉": "yòu",
    "鸩": "zhèn",
    "髟": "biāo",
    "酿": "niàng",
    "仄": "zè",
    "倮": "luǒ",
    "釐": "lí",
    "刷": "shuā / shuà",
    "瑗": "yuàn",
    "诨": "hùn",
    "链": "liàn",
    "阍": "hūn",
    "钮": "nǐu",
    "寮": "liáo",
    "鹉": "wǔ",
    "甯": "níng",
    "瞥": "piē",
    "谶": "chèn",
    "铉": "xuàn",
    "刖": "yuè",
    "榭": "xiè",
    "晶": "jīng",
    "觇": "zhān / chān",
    "黼": "fǔ",
    "湍": "tuān",
    "泳": "yǒng",
    "俳": "pái",
    "遑": "huáng",
    "胍": "guā",
    "趺": "fū",
    "礁": "jiāo",
    "脯": "fǔ / pú",
    "缆": "làn / lǎn",
    "浜": "bāng",
    "帏": "wéi",
    "涪": "fú",
    "怿": "yì",
    "铝": "lǔ: / lv",
    "铅": "qiān",
    "苔": "tāi / tái",
    "驷": "sì",
    "鹧": "zhè",
    "脏": "zāng / zàng",
    "呶": "náo",
    "袤": "mào",
    "蔷": "qiáng",
    "塌": "tā",
    "龛": "kān",
    "跄": "qiāng / qiàng",
    "淠": "pì",
    "鞴": "bèi",
    "箍": "gū",
    "偾": "fèn",
    "烽": "fēng",
    "隗": "wěi",
    "蚩": "chī",
    "鼋": "yuán",
    "捌": "bā",
    "佚": "yì",
    "娃": "wá",
    "睬": "cǎi",
    "淝": "féi",
    "虺": "huī / huǐ",
    "疵": "cī",
    "惕": "tì",
    "罡": "gāng",
    "鲇": "nián",
    "穗": "suì",
    "鲆": "píng",
    "醺": "xūn",
    "盅": "zhōng",
    "诎": "qū",
    "缟": "gǎo",
    "珏": "jué",
    "蠛": "miè",
    "霭": "ǎi",
    "厕": "cè",
    "佗": "tuó",
    "茏": "lóng",
    "瘸": "qué",
    "垡": "fá",
    "莞": "guān / guǎn / wǎn",
    "弋": "yì",
    "湎": "miǎn",
    "嫦": "cháng",
    "笤": "tiáo",
    "郸": "dān",
    "谍": "dié",
    "霓": "ní",
    "媸": "chī",
    "虿": "chài",
    "鐸": "duó",
    "矮": "ǎi",
    "畚": "běn",
    "缭": "liáo",
    "缣": "jiān",
    "坞": "wù",
    "愣": "lèng",
    "档": "dàng",
    "哂": "shěn",
    "鼐": "nài",
    "湓": "pén",
    "汰": "tài",
    "墼": "jī",
    "罱": "lǎn",
    "窕": "tiǎo",
    "隰": "xí",
    "囟": "xìn",
    "濯": "zhuó",
    "甜": "tián",
    "粱": "liáng",
    "蔑": "miè",
    "组": "zǔ",
    "惆": "chóu",
    "鼙": "pí",
    "蚧": "jiè",
    "镶": "xiāng",
    "悸": "jì",
    "陡": "dǒu",
    "涡": "guō / wō",
    "肢": "zhī",
    "淞": "sōng",
    "鞑": "dá",
    "祎": "yī",
    "矿": "kuàng",
    "锸": "chā",
    "衲": "nà",
    "描": "miáo",
    "鸵": "tuó",
    "菸": "yān",
    "蚓": "yǐn",
    "笕": "jiǎn",
    "讦": "jié",
    "菀": "wǎn",
    "噜": "lū",
    "窠": "kē",
    "涠": "wéi",
    "踞": "jù",
    "鄄": "juàn",
    "舸": "gě",
    "钅": "jīn",
    "聂": "niè",
    "泡": "pāo / pào",
    "蹊": "xī / qī",
    "谆": "zhūn",
    "裆": "dāng",
    "脩": "yǒu",
    "蔓": "mán / màn",
    "萑": "huán",
    "喏": "rě / nuò",
    "婷": "tíng",
    "泵": "bèng",
    "讪": "shàn",
    "硪": "wò",
    "畛": "zhěn",
    "鹨": "lìu",
    "滤": "lù: / lv",
    "笊": "zhào",
    "倜": "tì",
    "喑": "yīn",
    "孀": "shuāng",
    "迢": "tiáo",
    "逛": "guàng",
    "砌": "qì",
    "妍": "yán",
    "暧": "ài",
    "粹": "cuì",
    "恽": "yùn",
    "咚": "dōng",
    "猥": "wěi",
    "膀": "bǎng / bàng / pāng / páng",
    "豺": "chái",
    "侗": "dòng / tóng",
    "乩": "jī",
    "馕": "náng",
    "蟮": "shàn",
    "淇": "qí",
    "铢": "zhū",
    "腋": "yè",
    "宓": "mì",
    "锷": "è",
    "踅": "chì / xué",
    "鄯": "shàn",
    "嗑": "kè / kē",
    "祧": "tiāo",
    "呃": "è / e",
    "魉": "liǎng",
    "偻": "lóu / lv",
    "炯": "jiǒng",
    "暌": "kuí",
    "歧": "qí",
    "谰": "lán",
    "诊": "zhěn",
    "刎": "wěn",
    "碟": "dié",
    "瑛": "yīng",
    "滁": "chú",
    "刈": "yì",
    "弭": "mǐ",
    "胗": "zhēn",
    "蟀": "shuài",
    "裟": "shā",
    "剐": "guǎ",
    "葡": "pú",
    "浒": "hǔ",
    "匕": "bī / bǐ",
    "愠": "yùn",
    "苹": "pín / píng",
    "镉": "gé",
    "辣": "là",
    "痊": "quán",
    "牺": "xī",
    "阗": "tián",
    "桨": "jiǎng",
    "箴": "zhēn",
    "翳": "yì",
    "玮": "wěi",
    "缁": "zī",
    "墉": "yōng",
    "稔": "rěn",
    "袈": "jiā",
    "澧": "lǐ",
    "岗": "gǎng",
    "薇": "wēi",
    "觊": "jì",
    "浯": "wú",
    "曦": "xī",
    "髅": "lóu",
    "唧": "jī",
    "莩": "fú / piǎo",
    "嗨": "hāi / hēi",
    "垫": "diàn",
    "舷": "xián",
    "沅": "yuán",
    "锄": "chú",
    "仞": "rèn",
    "崧": "sōng",
    "戢": "jí",
    "啜": "chuò",
    "旰": "gàn",
    "钭": "tǒu",
    "蘧": "qú",
    "埠": "bù",
    "疚": "jìu",
    "笋": "sǔn",
    "甓": "pì",
    "蛄": "gū",
    "紊": "wěn / wèn",
    "绡": "xiāo",
    "稠": "chóu",
    "崛": "jué",
    "盱": "xū",
    "钌": "liǎo",
    "盂": "yú",
    "蒯": "kuǎi",
    "缵": "zuǎn",
    "馐": "xīu",
    "樗": "chū",
    "褫": "chǐ",
    "萁": "qí",
    "浞": "zhuó",
    "逅": "hòu",
    "敉": "mǐ",
    "撺": "cuān",
    "凼": "dàng",
    "蝇": "yíng",
    "肘": "zhǒu",
    "蠊": "lián",
    "鲸": "jīng",
    "慵": "yōng",
    "轲": "kē",
    "旆": "pèi",
    "矍": "jué",
    "殒": "yǔn",
    "蚬": "xiǎn",
    "诃": "hē",
    "雩": "yú",
    "亵": "xiè",
    "嵋": "méi",
    "溲": "sōu",
    "糖": "táng",
    "吣": "qìn",
    "筝": "zhēng",
    "骰": "tóu",
    "霉": "méi",
    "赝": "yàn",
    "菁": "jīng",
    "嵬": "wéi",
    "蚪": "dǒu",
    "翕": "xì / xī",
    "泸": "lú",
    "绒": "róng",
    "绐": "dài",
    "潢": "huáng",
    "胨": "dòng",
    "鹆": "yù",
    "忱": "chén",
    "杉": "shā / shān",
    "诶": "ēi",
    "粝": "lì",
    "隼": "sǔn",
    "咂": "zā",
    "陉": "xíng",
    "苡": "yǐ",
    "魍": "wǎng",
    "烘": "hōng",
    "歼": "jiān",
    "岔": "chà",
    "渍": "zì",
    "郦": "lì",
    "靼": "dá",
    "剔": "tī",
    "缬": "xié",
    "砥": "dǐ",
    "魈": "xiāo",
    "瓷": "cí",
    "憬": "jǐng",
    "洵": "xún",
    "攵": "fǎn",
    "跎": "tuó",
    "笨": "bèn",
    "馍": "mó",
    "髓": "suǐ",
    "缌": "sī",
    "曙": "shǔ",
    "揉": "róu",
    "竣": "nan",
    "艉": "wěi",
    "钣": "bǎn",
    "沤": "ōu / òu",
    "膂": "lǔ: / lv",
    "朦": "méng",
    "眇": "miǎo",
    "搴": "qiān",
    "咫": "zhǐ",
    "羝": "dī",
    "纽": "nǐu",
    "濡": "rú",
    "玷": "diàn",
    "猖": "chāng",
    "俐": "lì",
    "溶": "róng",
    "嘟": "dū",
    "嗌": "ài",
    "鬯": "chàng",
    "嘣": "bēng",
    "泓": "hóng",
    "侦": "zhēn",
    "嬗": "shàn",
    "裸": "luǒ",
    "蚤": "zǎo",
    "圉": "yǔ",
    "芟": "shān",
    "葑": "fēng",
    "飧": "sūn",
    "齑": "jī",
    "峙": "zhì",
    "榱": "cuī",
    "龊": "chuò",
    "竽": "yú",
    "鞒": "qiáo",
    "镠": "liáo",
    "巽": "xùn",
    "槽": "cáo",
    "萝": "luó",
    "獗": "jué",
    "玑": "jī",
    "榛": "zhēn",
    "肷": "qiǎn",
    "骶": "dǐ",
    "藁": "gǎo",
    "樯": "qiáng",
    "癖": "pǐ",
    "廿": "niàn",
    "苋": "xiàn",
    "夥": "huǒ",
    "殇": "shāng",
    "郗": "chī / xī",
    "馁": "něi",
    "芰": "jì",
    "纛": "dào",
    "赙": "fù",
    "臬": "niè",
    "诼": "zhuó",
    "槎": "chá",
    "肫": "zhūn",
    "舐": "shì",
    "禋": "yīn",
    "绊": "bàn",
    "瓢": "piáo",
    "萄": "táo",
    "莼": "chún",
    "蕤": "ruí",
    "瞑": "míng",
    "喾": "kù",
    "燥": "zào",
    "瞽": "gǔ",
    "摔": "shuāi",
    "阌": "wén",
    "畲": "yú / shē",
    "蹶": "jué / juě",
    "企": "qǐ",
    "庥": "xīu",
    "栉": "zhì",
    "鞔": "mán",
    "霹": "pī",
    "窒": "zhì",
    "葆": "bǎo",
    "纮": "hóng",
    "宙": "zhòu",
    "縻": "mí",
    "阊": "chāng",
    "痈": "yōng",
    "傧": "bīn",
    "慑": "shè",
    "抻": "chēn",
    "焐": "wù",
    "祟": "suì",
    "葺": "qì",
    "僵": "jiāng",
    "堇": "jǐn",
    "槌": "chuí",
    "葭": "jiā",
    "甑": "zèng",
    "棉": "mián",
    "啄": "zhuó",
    "饫": "yù",
    "鹩": "liáo",
    "颤": "zhàn / chàn",
    "乒": "pīng",
    "炒": "chǎo",
    "芾": "fèi / fú",
    "眸": "móu",
    "炬": "jù",
    "腻": "nì",
    "翎": "líng",
    "鞣": "róu",
    "薜": "bì",
    "焱": "yàn",
    "犍": "jiān",
    "瘠": "jí",
    "伫": "zhù",
    "萋": "qī",
    "镕": "róng",
    "嗲": "diǎ",
    "迓": "yà",
    "槁": "gǎo",
    "箧": "qiè",
    "蘸": "zhàn",
    "汁": "zhī",
    "懔": "lǐn",
    "炫": "xuàn",
    "肜": "róng",
    "苫": "shān",
    "舻": "lú",
    "笱": "gǒu",
    "灞": "bà",
    "苴": "jū",
    "嗷": "áo",
    "汜": "sì",
    "雏": "chú",
    "螺": "luó",
    "啾": "jīu",
    "砀": "dàng",
    "楞": "léng",
    "芗": "xiāng",
    "沆": "hàng",
    "芏": "dù",
    "觌": "dí",
    "赁": "lìn",
    "喟": "kuì",
    "隳": "huī",
    "湔": "jiān",
    "蚯": "qīu",
    "踝": "huái",
    "驺": "zōu",
    "胀": "zhàng",
    "颦": "pín",
    "鼍": "tuó",
    "褰": "qiān",
    "钚": "bù",
    "锼": "sōu",
    "郾": "yǎn",
    "呱": "gū / guā",
    "嵊": "shèng",
    "鹾": "cuó",
    "跫": "qióng",
    "胱": "guāng",
    "髁": "kē",
    "滇": "diān",
    "薏": "yì",
    "恿": "yǒng",
    "蚣": "gōng",
    "蚱": "zhà",
    "岘": "xiàn",
    "裢": "lián",
    "龆": "tiáo",
    "枫": "fēng",
    "哇": "wā / wa",
    "厣": "yǎn",
    "芨": "jí / jī",
    "婵": "chán",
    "甭": "béng",
    "锻": "duàn",
    "醵": "jù",
    "咀": "jǔ",
    "剃": "tì",
    "硎": "xíng",
    "獬": "xiè",
    "粕": "pò",
    "肽": "tài",
    "雳": "lì",
    "乇": "tuō",
    "肓": "huāng",
    "殂": "cú",
    "舳": "zhú",
    "榇": "chèn",
    "蚌": "bàng",
    "鸷": "zhì",
    "莸": "yóu",
    "呛": "qiāng / qiàng",
    "侑": "yòu",
    "黥": "qíng",
    "侬": "nóng",
    "旖": "yǐ",
    "蚰": "yóu",
    "纺": "fǎng",
    "烬": "jìn",
    "悚": "sǒng",
    "謇": "jiǎn",
    "霾": "nan",
    "髌": "bìn",
    "樾": "yuè",
    "铰": "jiǎo",
    "猝": "cù",
    "泠": "líng",
    "粼": "lín",
    "锒": "láng",
    "痰": "tán",
    "鼗": "táo",
    "鄣": "zhāng",
    "胝": "zhī",
    "踱": "duó",
    "仝": "tóng",
    "钳": "qián",
    "厍": "shè",
    "滂": "pāng",
    "昃": "zè",
    "煦": "xù",
    "踰": "yáo",
    "骷": "kū",
    "唆": "suō",
    "芽": "yá",
    "饩": "xì",
    "癯": "qú",
    "茔": "yíng",
    "摊": "tān",
    "亓": "qí",
    "呒": "fǔ / mú",
    "骘": "zhì",
    "禺": "yú",
    "荤": "hūn",
    "嗥": "háo",
    "眙": "yí",
    "鹪": "jiāo",
    "碓": "duì",
    "镖": "biāo",
    "荅": "dá",
    "婪": "lán",
    "稣": "sū",
    "酺": "pú",
    "匦": "guǐ",
    "卟": "bǔ",
    "崞": "guō",
    "疟": "nuè / yào",
    "嗾": "sǒu",
    "讵": "jù",
    "涩": "sè",
    "摭": "zhí",
    "闶": "kāng",
    "笈": "jí",
    "淀": "diàn",
    "焖": "mèn",
    "骼": "gé",
    "玖": "jǐu",
    "卡": "kǎ / qiǎ",
    "茄": "qié",
    "驶": "shǐ",
    "珑": "lóng",
    "虼": "gè",
    "栊": "lóng",
    "绖": "dié",
    "码": "mǎ",
    "塑": "sù",
    "妲": "dá",
    "磷": "lín",
    "吻": "wěn",
    "耘": "yún",
    "褡": "dā",
    "鲈": "lú",
    "胞": "bāo",
    "讣": "fù",
    "羔": "gāo",
    "耪": "pǎng",
    "瓠": "hù",
    "霰": "xiàn",
    "飒": "sà",
    "跽": "jì",
    "黾": "mǐn / miǎn",
    "馊": "sōu",
    "虮": "jǐ",
    "筘": "kòu",
    "玲": "líng",
    "嘏": "gǔ / jiǎ",
    "芫": "yuán",
    "扩": "kuò",
    "涝": "lào",
    "劬": "qú",
    "窭": "jù",
    "蟊": "máo",
    "醭": "bú",
    "辫": "biàn",
    "吭": "háng / kēng",
    "嘧": "mì",
    "麈": "zhǔ",
    "缡": "lí",
    "涅": "niè",
    "蒿": "hāo",
    "璜": "huáng",
    "虻": "méng",
    "衽": "rèn",
    "芭": "bā",
    "柘": "zhè",
    "楣": "méi",
    "榔": "láng",
    "琚": "jū",
    "龉": "yǔ",
    "慝": "tè",
    "摈": "bìn",
    "呓": "yì",
    "浠": "xī",
    "赭": "zhě",
    "嵛": "yú",
    "沱": "tuó",
    "娴": "xián",
    "黠": "xiá",
    "郃": "xiá",
    "钕": "nǔ: / nv",
    "啪": "pā",
    "蚊": "wén",
    "漾": "yàng",
    "睾": "gāo",
    "窬": "yú",
    "凸": "tū",
    "禳": "ráng",
    "晤": "wù",
    "靳": "jìn",
    "墅": "shù",
    "圩": "wéi / xū",
    "嗬": "hē",
    "璨": "càn",
    "铄": "shuò",
    "锨": "xiān",
    "坂": "bǎn",
    "咛": "níng",
    "悛": "quān",
    "暾": "tūn",
    "馗": "kuí",
    "烊": "yáng",
    "溯": "sù",
    "帚": "zhǒu",
    "芡": "qiàn",
    "岌": "jí",
    "罅": "xià",
    "郯": "tán",
    "啮": "niè",
    "眯": "mī / mǐ",
    "锶": "sī",
    "跹": "xiān",
    "孥": "nú",
    "遄": "chuán",
    "馄": "hún",
    "秣": "mò",
    "穸": "xī",
    "炔": "quē / guì",
    "惴": "zhuì",
    "硖": "xiá",
    "瓣": "bàn",
    "釜": "fǔ",
    "糠": "kāng",
    "漓": "lí",
    "孪": "luán",
    "翡": "fěi",
    "鲂": "fáng",
    "僬": "jiāo",
    "祏": "shí",
    "蛱": "jiá",
    "杠": "gāng / gàng",
    "鄞": "yín",
    "峄": "yì",
    "忏": "chàn",
    "蚋": "ruì",
    "藐": "miǎo",
    "菡": "hàn",
    "怆": "chuàng",
    "瞅": "chǒu",
    "愦": "kuì",
    "屿": "yǔ",
    "窳": "yǔ",
    "羧": "suō",
    "筐": "kuāng",
    "缇": "tí",
    "砩": "fèi / fú",
    "悫": "què",
    "窆": "biǎn",
    "届": "jiè",
    "梭": "suō",
    "趸": "dǔn",
    "扪": "mén",
    "烨": "yè",
    "袼": "gē",
    "甙": "dài",
    "沥": "lì",
    "娣": "dì",
    "哽": "gěng",
    "峪": "yù",
    "酆": "fēng",
    "槠": "zhū",
    "廨": "xiè",
    "綦": "qí",
    "趴": "pā",
    "婀": "ē",
    "嫠": "lí",
    "鹚": "cí",
    "肄": "yì",
    "凫": "fú",
    "菰": "gū",
    "佬": "lǎo",
    "俑": "yǒng",
    "髑": "dú",
    "貉": "háo / hé / mò",
    "尿": "suī / niào",
    "浃": "jiā",
    "柚": "yòu",
    "憨": "hān",
    "缒": "zhuì",
    "杼": "zhù",
    "畈": "fàn",
    "雎": "jū",
    "遘": "gòu",
    "卉": "huì",
    "缃": "xiāng",
    "煽": "shān",
    "蛛": "zhū",
    "怙": "hù",
    "橙": "chéng",
    "阈": "yù",
    "艚": "cáo",
    "渑": "shéng / miǎn",
    "杓": "biāo / sháo",
    "钝": "dùn",
    "艿": "nǎi",
    "嵘": "róng",
    "缜": "zhěn",
    "氡": "dōng",
    "檎": "qín",
    "樟": "zhāng",
    "胩": "kǎ",
    "谳": "yàn",
    "濒": "bīn",
    "赊": "shē",
    "逭": "huàn",
    "氪": "kè",
    "诂": "gǔ",
    "簋": "guǐ",
    "槲": "hú",
    "闇": "ān",
    "澡": "zǎo",
    "娲": "wā",
    "锩": "juàn / juǎn",
    "璩": "qú",
    "蚍": "pí",
    "鏊": "ào",
    "芩": "qín",
    "莨": "làng",
    "喔": "ō / wō",
    "嵇": "jī",
    "莎": "shā / suō",
    "罐": "guàn",
    "敫": "jiǎo",
    "畀": "bì",
    "聋": "lóng",
    "沫": "mò",
    "萸": "yú",
    "焯": "chāo",
    "哎": "āi",
    "茧": "jiǎn",
    "炷": "zhù",
    "疃": "tuǎn",
    "萘": "nài",
    "崾": "yǎo",
    "饨": "tún",
    "洙": "zhū",
    "粽": "zòng",
    "楮": "chǔ",
    "罘": "fú",
    "糯": "nuò",
    "胭": "yān",
    "碣": "jié",
    "蜓": "tíng",
    "嗫": "niè",
    "苄": "biàn",
    "柰": "nài",
    "蘅": "héng",
    "岬": "jiǎ",
    "榧": "fěi",
    "鹕": "hú",
    "锫": "péi",
    "跞": "lì",
    "灸": "jǐu",
    "蜗": "wō",
    "赟": "yūn",
    "锖": "qiāng",
    "蓦": "mò",
    "簌": "sù",
    "腑": "fǔ",
    "煸": "biān",
    "鹜": "wù",
    "炱": "tái",
    "枋": "fāng",
    "鸺": "xīu",
    "啡": "fēi",
    "芹": "qín",
    "媵": "yìng",
    "橇": "qiāo",
    "呔": "tǎi",
    "轶": "yì",
    "麋": "mí",
    "訾": "zī / zǐ",
    "陲": "chuí",
    "糇": "hóu",
    "箓": "lù",
    "烀": "hū",
    "镀": "dù",
    "辗": "zhǎn / niǎn",
    "蹂": "róu",
    "缈": "miǎo",
    "梵": "fàn",
    "缋": "huì",
    "谲": "jué",
    "腴": "yú",
    "餮": "tiè",
    "鳏": "guān",
    "氓": "máng / méng",
    "嫱": "qiáng",
    "昝": "zǎn",
    "泺": "luò",
    "榴": "líu",
    "锊": "luè",
    "龈": "kěn / yín",
    "骱": "xiè / jiè",
    "韫": "yùn",
    "拄": "zhǔ",
    "瀚": "hàn",
    "缑": "gōu",
    "爨": "cuàn",
    "汕": "shàn",
    "芑": "qǐ",
    "囿": "yòu",
    "劢": "nan",
    "眺": "tiào",
    "缱": "qiǎn",
    "锎": "kāi",
    "窑": "yáo",
    "绲": "gǔn",
    "裱": "biǎo",
    "岢": "kě",
    "槿": "jǐn",
    "龌": "wò",
    "骖": "cān",
    "妣": "bǐ",
    "馘": "guó",
    "呦": "yōu",
    "哝": "nóng",
    "殚": "dān",
    "耒": "lěi",
    "龅": "páo / bāo",
    "珩": "héng",
    "伉": "kàng",
    "胂": "shèn",
    "菪": "dàng",
    "罍": "léi",
    "蹬": "dèng / dēng",
    "袴": "kù",
    "儋": "dān",
    "舄": "xì",
    "嘛": "ma",
    "豚": "tún",
    "鞲": "gōu",
    "啐": "cuì",
    "彘": "zhì",
    "窨": "xūn / yìn",
    "龃": "jǔ",
    "镁": "měi",
    "朊": "ruǎn",
    "锯": "jū / jù",
    "揩": "kāi",
    "槔": "gāo",
    "鲠": "gěng",
    "皿": "mǐn",
    "韧": "rèn",
    "蛰": "zhé / zhí",
    "蛏": "chēng",
    "戡": "kān",
    "薷": "rú",
    "掎": "jǐ",
    "卺": "jǐn",
    "蚶": "hān",
    "怔": "zhēng",
    "祺": "qí",
    "蘩": "fán",
    "憩": "qì",
    "黩": "dú",
    "蝴": "hú",
    "崎": "qí",
    "谚": "yàn",
    "愎": "bì",
    "赧": "nǎn",
    "椽": "chuán",
    "叽": "jī",
    "襦": "rú",
    "藿": "huò",
    "妤": "yú",
    "愀": "qiǎo",
    "舂": "chōng",
    "趱": "zǎn",
    "錾": "zàn",
    "篚": "fěi",
    "呻": "shēn",
    "畎": "quǎn",
    "柿": "shì",
    "濂": "lián",
    "枰": "píng",
    "氅": "chǎng",
    "舁": "yú",
    "嘘": "xū",
    "乜": "miē / niè",
    "跬": "kuǐ",
    "搠": "shuò",
    "璁": "cōng",
    "讬": "tuō",
    "坷": "kě",
    "馒": "mán",
    "藓": "xiǎn",
    "螭": "chī",
    "艟": "chōng",
    "捺": "nà",
    "峋": "xún",
    "恹": "yān",
    "迕": "wǔ",
    "觳": "hú",
    "铿": "kēng",
    "篙": "gāo",
    "嗵": "tōng",
};